### ISSUE TITLE
"Remember me" not working

### ISSUE THREAD

**Issue by keeneyemedia** [jfarthing84/theme-my-login#1]
With a vanilla install of TML, checking the box "Remember Me" has no effect on future login attempts. Both the "username" and "password" fields remain blank when attempting to login again.

**Comment by jfarthing84** [comment]
The remember me checkbox extends the length of the login cookie for 15 days. This means that as long as you don't click "Log out" or clear your cookies, you'll be logged in automatically whenever you visit your site. It doesn't autofill your login form, that is a browser function.

**Comment by keeneyemedia** [comment]
Thanks for the explanation. Much appreciated.
