### ISSUE TITLE
Wrong email?

### ISSUE THREAD

**Issue by paganJim** [jfarthing84/theme-my-login#101]
I have something that is annoying me.

When someone signs up for my site, they enter a password as part of the process.

The formatting of the email is atrocious but I will fix that in a minute as soon as I get done here. But the problem is the email says:
"Username: jdoe To set your password, visit the following address: http://jimandms.com/resetpass/?key=Kigop86E0c3ENuOpGBnl&login=jdoe http://jimandms.com/login/"

They have already set their pw when they went through registration. Why would they get an email telling them to go to a link to set their pw?

Thanks for looking!
Jim

**Comment by jfarthing84** [comment]
This is by design. If you want to change the email, use the Custom E-mail module.
