### ISSUE TITLE
Title not hiding

### ISSUE THREAD

**Issue by planktonWD** [jfarthing84/theme-my-login#102]
Hi guys,

I have the following in my template

```
<?php if (!function_exists('dynamic_sidebar') || !dynamic_sidebar('register')) : ?>
```
and in my widget I have the title hidden which is working however I am not getting any error messages showing at all.

I tried swapping out this code for the shortcode:
```
<?php echo do_shortcode('[theme-my-login instance="1" default_action="register" show_title="false" show_log_link="false" show_pass_link="false"]'); ?>
```
The error message appear fine now but hiding the login, password and title is not working.

Thanks,

Mike
![screen shot 2017-01-06 at 12 20 26 pm](https://cloud.githubusercontent.com/assets/1151897/21701508/df99b50a-d40a-11e6-9f07-85255a3b464f.png)

**Comment by jfarthing84** [comment]
Shortcodes require booleans to be numeric. Use 0 for false and 1 for true.
