### ISSUE TITLE
TFA works on Page but not on Widget

### ISSUE THREAD

**Issue by micha1848** [jfarthing84/theme-my-login#103]
Hi,
the Plugin [Two Factor Authentication](https://de.wordpress.org/plugins/two-factor-authentication/) works fine with the Login Page created with your Plugin.
But the Widget only repeat the Loginform.

**Comment by micha1848** [comment]
seems not a Problem with TFA and TML, it seems a Problem of the TML Widget.
See: #104

**Comment by DavidAnderson684** [comment]
This works in the current release of the TFA plugin.

**Comment by micha1848** [comment]
Sorry for that, i test it on an Blank System, without any activated Plugins.
Only my Theme was active.
And it seems, that there are the Problem. 
With the WP Standard Theme it works like a charme.
So i close the Issue.
