### ISSUE TITLE
Widget dont work

### ISSUE THREAD

**Issue by micha1848** [jfarthing84/theme-my-login#104]
the Widget of TML produce only "invalid User / PW" (seen at the Logfiles) on Login.

The Login from the Form of TML works correct.

**Comment by jfarthing84** [comment]
Have you tried disabling other plugins?

**Comment by micha1848** [comment]
Sorry for that, i test it on an Blank System, without any activated Plugins.
Only my Theme was active. And it seems, that there are the Problem. 
With the WP Standard Theme it works like a charme.
So i close the Issue.
