### ISSUE TITLE
Hiding menu item for users not logged in

### ISSUE THREAD

**Issue by tnaoesting** [jfarthing84/theme-my-login#106]
Hi Jeff,
The plugin is great and has been working VERY WELL for us.  In reading the documentation and wordpress forums, I got the impression that we could put a menu item as a submenu under the "logout" menu item, and it would only show up for those logged in.  However, the submenu item shows up for those NOT logged in and is placed at the end of our top level menu structure.  Essentially, it is a link to the persons profile.  We wanted to have a way for those logged in to navigate back to their profile page should they be moving around on our other content, but we only wanted it to appear for those logged in.  Please see the attached photos of the menus when logged in and logged out.
![loggedinmenu](https://cloud.githubusercontent.com/assets/16517221/22988386/e5845774-f37f-11e6-88a9-b0f5f7dd51a8.jpg)
![loggedoutmenu](https://cloud.githubusercontent.com/assets/16517221/22988385/e58164d8-f37f-11e6-8570-bc268d066f60.jpg)

Thanks for any help you can provide.
Regards,
Aaron

**Comment by jfarthing84** [comment]
This is a support request and would belong in the [forums](https://wordpress.org/support/plugin/theme-my-login).
