### ISSUE TITLE
No customization for "Notification of Password Change" email

### ISSUE THREAD

**Issue by TacoV** [jfarthing84/theme-my-login#110]
As of now, one automatic e-mail is not customizable: the Notification of Password Change. This is sent to a user whenever his/her password is changed.

There is an open (and conflicting) PR for this: https://github.com/jfarthing84/theme-my-login/pull/65
It's also mentioned in another issue https://github.com/jfarthing84/theme-my-login/issues/78#issuecomment-234730475

**Comment by TacoV** [comment]
For completeness (and memo to self) a link to an earlier discussion about this:
https://wordpress.org/support/topic/custom-reset-password-notification-e-mail/

Plus all the e-mails I think are/should be customizable (leaving out user moderation mails):

* **New user registers (mail to user + notification to admin)**
register_new_user (custom substitute for wp_send_new_user_notifications)
edit_user_created_user (custom substitute for wp_send_new_user_notifications)

* **User requests a reset link (mail to user)**
retrieve_password
retrieve_password_title (existing hook)
retrieve_password_message (existing hook)

* **User resets password (notification to admin)**
password_reset
after_password_reset (custom substitute for wp_password_change_notification)
password_change_notification etc (custom hooks , which can now become kind of confusing)

* **User changes password (mail to user)**
password_change_email (what to send)
send_password_change_email (whether to send)

* **User changes e-mail (mail to user)**
email_change_email (what to send)
send_email_change_email (whether to send)

**Comment by jfarthing84** [comment]
No longer relevant to 7+.
