### ISSUE TITLE
Conflict with the Members plugin

### ISSUE THREAD

**Issue by mihaijoldis** [jfarthing84/theme-my-login#112]
There is a weird redirect loop ocurring when both plugins are ativated (https://wordpress.org/plugins/members/) and when on the members plugin you enable the Private site option which basically does a redirect of all non logged in users to the login page.

I did some debugging and if removing all the code and leaving just the last return statement from this code block all is good 
https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login.php#L661

**Comment by jfarthing84** [comment]
Have you tried using TML's private site option instead?

**Comment by jfarthing84** [comment]
Closing this issue as I have not heard back from you.
