### ISSUE TITLE
Display more than one shortcode on pages created by default

### ISSUE THREAD

**Issue by mfka** [jfarthing84/theme-my-login#115]
Hi there @jfarthing84 ,
thank you very much for your efforts in creating plugin! It is great tool and helps me very much! I just encountered a problem! When I tried to put two shortcodes on e.g /login page - it works till i push confirm button of the second shortcode. Because it is switch the first (default added) shortcode to action of the submited one. Here some example:
My /login page:
[theme-my-login ]
[theme-my-login default_action='register']

when i click on "register" it will change my first form to register form (not login form).

The solution which I found it is to change argument in shortcode(); function:
Your code: 
/theme-my-login/includes/class-theme-my-login.pl
`if ( !empty( $this->request_action ) ){ $atts[ 'default_action' ] = $this->request_action;}}`

my proposition - resolve: 
`if ( !empty( $this->request_action ) ){ $atts[ 'default_action' ] = self::get_page_action( get_the_ID());}}`

I just writing to get confirmation if I solve the problem - or I just ruined your work :( Please let me know how to solve the problem in other way - to have two shortcode on one of the default pages.

Thanks a lot!

**Comment by jfarthing84** [comment]
This actually seems like more of a support question. Please use the [forum](https://wordpress.org/support/plugin/theme-my-login).
