### ISSUE TITLE
Error in call to function "switch_to_blog"

### ISSUE THREAD

**Issue by acarravedo** [jfarthing84/theme-my-login#116]
The "**network_site_url**" function of the "**Theme_My_Login_MS_Signup**" class located in the "**theme-my-login / includes / class-theme-my-login-ms-signup.php**" file has a call to the "switch_to_blog" function.

In this call is forcing the value "1" to identify the "blog" which causes a "recursive" error to appear in the whole system if this Blog ID is not being used.

**Comment by jfarthing84** [comment]
Can you verify if changing [this line](https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login-ms-signup.php#L546) to the following fixes the issue?

`switch_to_blog( get_network()->id );`
