### ISSUE TITLE
Shortcode display code does not get instance

### ISSUE THREAD

**Issue by produktive** [jfarthing84/theme-my-login#119]
I am using the shortcode on my login page `[theme-my-login instance="portal"]`. In my custom functions plugin I was checking what was returning in the callback variables:
```
function tml_action_url( $url, $action, $instance ) {
	if ( $action == 'register' ) {
		$url = site_url().'?url='.$url.'&action='.$action.'&instance='.$instance;
	}
	return $url;
}
add_filter( 'tml_action_url', 'tml_action_url', 10, 3 );
```
Which turns my link into: http://www.example.com/?url=http://www.example.com/register/&action=register&instance=login

First of all, http://www.example.com/register/ is not the page that this shortcode is being displayed on. Why is it returning that URL? Second, why is $instance returning 'login'? Shouldn't it be 'portal'? What am I doing wrong?

**Comment by jfarthing84** [comment]
The filter `tml_action_url` takes 4 parameters: https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login-template.php#L266

**Comment by produktive** [comment]
I changed the function to include 4 variables and changed the 3 to a 4 in the filter but instance always equals 1. It doesn't matter what I set instance to in the shortcode, it always seems to equal 1.
