### ISSUE TITLE
theme my login default role is not pending

### ISSUE THREAD

**Issue by sampath1988** [jfarthing84/theme-my-login#120]
I am using theme my login for my Q&A web site. When a user is first registered I want that user to be a pending user until he/she confirms his/her mail address. I have set the TML settings accordingly but unfortunately when a new user is registered, the immediate user role is 'subscriber' and not 'pending'. [WP admin dash board shows the new user role as subscriber.] and this enables the new user to log in to the site without verifying his/her mail address. 
Please suggest a workaround for this as I badly need this functionality for my site and thanks in advance.

**Comment by jfarthing84** [comment]
Support requests belong here: https://wordpress.org/support/plugin/theme-my-login
