### ISSUE TITLE
Registration link

### ISSUE THREAD

**Issue by motorcityfilms** [jfarthing84/theme-my-login#122]
The registration link and “lost password” below login on the site i’m building won’t work correctly. It redirects to:
“website”?redirect_to=%2Flogin%2Fregister%2F&reauth=1
which is the login page, saying “please log in to continue”

PLEASE ADVISE ASAP!

**Comment by jfarthing84** [comment]
The proper forum for support is [here](https://wordpress.org/support/plugin/theme-my-login).
