### ISSUE TITLE
Translating emails with WPML

### ISSUE THREAD

**Issue by dgwatkins** [jfarthing84/theme-my-login#123]
There are a few reports of emails not being translated with WPML:

https://wordpress.org/support/topic/wpml-translation-of-custom-emails/
https://wpml.org/forums/topic/theme-my-login-custom-emails-translations-are-not-used-in-the-actual-sent-emails/

**Comment by jfarthing84** [comment]
As this is all subject to change with the next major version, for now, users can probably apply your method using `theme-my-login-custom.php`.
