### ISSUE TITLE
issue with wpml - themed profiles

### ISSUE THREAD

**Issue by marcin-biegun** [jfarthing84/theme-my-login#125]
Themed profiles works only in main language, in 2nd language instead of profile edit it gives login form even though user is logged in. 
`		if ( Theme_My_Login::is_tml_page() ) {`
gives false for 2nd language but not sure where / how to solve

**Comment by jfarthing84** [comment]
The proper forum for support is [here](https://wordpress.org/support/plugin/theme-my-login).
