### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by fmarzocca** [jfarthing84/theme-my-login#126]
Hi,
I am in the need of let users change their passwords with a double-entry of the password to avoid typos.
Looking at your template, I have seen that the resetpass-form.php is coded in this way, but when I activate it, I am facing a “Lost Password” form, with the email link to be sent.

How can I display the form with the “confirm new password” field?

Thanks

**Comment by jfarthing84** [comment]
The proper forum for support is [here](https://wordpress.org/support/plugin/theme-my-login).
