### ISSUE TITLE
Admin approval email not being sent

### ISSUE THREAD

**Issue by cnrgcentral** [jfarthing84/theme-my-login#128]
When a new user registered I am NOT receiving the admin email to tell me they have registered and need approval. 

I have disabled plugs - I have tried to sent member time to subscribers (saw in another forum) but nothing is working! 

All other emails are being sent. 

Please help

**Comment by cnrgcentral** [comment]
Can someone please help!

**Comment by jfarthing84** [comment]
The proper forum for support is [here](https://wordpress.org/support/plugin/theme-my-login).
