### ISSUE TITLE
theme-my-login-6.4-beta2.zip - cannot activate

### ISSUE THREAD

**Issue by slmoore** [jfarthing84/theme-my-login#13]
Hey Jeff, after uploading theme-my-login-6.4-beta2.zip, the activation posts this error:

Plugin could not be activated because it triggered a fatal error.

Warning: require_once(.../wp-content/plugins/theme-my-login/includes/class-theme-my-login-common.php): failed to open stream: No such file or directory in .../wp-content/plugins/theme-my-login-6.4-beta2/theme-my-login.php on line 18

Fatal error: require_once(): Failed opening required '.../wp-content/plugins/theme-my-login/includes/class-theme-my-login-common.php' (include_path='.:/usr/share/php:/usr/share/pear') in .../wp-content/plugins/theme-my-login-6.4-beta2/theme-my-login.php on line 18

**Comment by slmoore** [comment]
Found the answer on the support threads: 1) unzip the file; 2) rename the directory theme-my-login; 3) rezip the directory and install/activate.

https://wordpress.org/support/topic/compatibility-with-wordpress-43-44

**Comment by testad** [comment]
Have the same issue, thank you for sharing the fix.
