### ISSUE TITLE
'instance' shortcode attribute ignored for main TML instance

### ISSUE THREAD

**Issue by unixtam** [jfarthing84/theme-my-login#130]
Steps to reproduce:

1. Add TML shortcode to /login/ page.
2. Add TML shortcode to other page.
3. Log in on other page with false credentials.
4. Redirected to /login/, but no error message is shown.

This has been [reported elsewhere](https://wordpress.org/support/topic/login-form-on-multiple-pages-error-message-handling/), but not yet been resolved.

**Comment by jfarthing84** [comment]
This is by design. The main instance should always be "0".

**Comment by unixtam** [comment]
@jfarthing84, in that case maybe the main instance should be able to display error messages from other instances. Let me illustrate the issue with a real world example. I'm embedding a TML login form on the BuddyPress account activation page, so that users can immediately log in after activating their accounts.

You can test this with any two WP pages, no BP required. One page `/login/`, which contains the `[theme-my-login]` shortcode, and another page `/activate/`, which also contains the `[theme-my-login]` shortcode.

Attempting to log in with an incorrect username/password on `/login/` displays an error message as expected.
Attempting to log in with an incorrect username/password on `/activate/` redirects to `/login/`, but does not display the expected error message.

Now, in the wordpress.org support forum link supplied above, you advised to set `instance="1"`. I have tried all combinations of instancing and upon that failing, I looked at the code. It's been a while since I opened this ticket, but I remember I could not find a way to make error messages work properly without modifying the code, hence I submitted a patch in PR #131.

Maybe you can think of a better way to make this work?

**Comment by jfarthing84** [comment]
Well, that shouldn't even happen at all. The redirect to `/login` is the problem, as the separate instance should be able to handle the request itself. Does this happen with other plugins disabled?

**Comment by unixtam** [comment]
I can reproduce the behavior on a 4.9.2 single site WP installation, all plugins disabled except for TML 6.4.10. Tested two different themes too and got the same result (TwentyFifteen 1.9 and TwentySeventeen 1.4).

**Comment by jfarthing84** [comment]
Interesting. Hopefully, I will be able to look at it over the weekend.

**Comment by unixtam** [comment]
That would be great. Let me know if I can be of assistance.

**Comment by unixtam** [comment]
Since I haven't heard back from you, I looked into it myself and I believe I found the bug and fixed it. I posted a new issue (#142) and a PR (#143). The fix is consistent with your earlier comment that the redirect to /login is the problem, and with the fact that the default action is 'login' in several other places.
