### ISSUE TITLE
Block IP Address from Login Page

### ISSUE THREAD

**Issue by ArctoranDev** [jfarthing84/theme-my-login#133]
Could you please add in a simple script that basically instead of just emailing us the IP Addresses trying to access our accounts some sort of redirect or ability to display a custom message on the login page instead? I am getting so fed up with continuously having to update my .htaccess file with new IP Addresses.

**Comment by ArctoranDev** [comment]
@jfarthing84 you just ignoring your issues now bc you seem to be posting updates but not answering any issues?

**Comment by jfarthing84** [comment]
Try WordFence.
