### ISSUE TITLE
I cant find the custom.php for adding new feilds to registration, 

### ISSUE THREAD

**Issue by aboutautomation** [jfarthing84/theme-my-login#134]
Still learning to code, 

just installed Theme My Login, was trying to follow[ documentation](http://docs.thememylogin.com/)
but the latest install doesnt include theme-my-login-custom.php. as stated in documentation
could someone please help me create one or supply one for me. 
was simply trying to add first and last name, and username to registration form.

am i missing something?

**Comment by jfarthing84** [comment]
You have to create it. Also, this is not the proper forum for support, this is: https://wordpress.org/support/plugin/theme-my-login
