### ISSUE TITLE
Super Admins are not recognised properly on Multisite

### ISSUE THREAD

**Issue by mikelittle** [jfarthing84/theme-my-login#135]
## Scenario:
* Multisite WordPress. 
* A sub-site has access to dashboard turned off for subscribers.
* A superadmin who is not a member of that site.

## What should happen:
The superadmin should have access to all sites, regardless of whether they have been explicitly aded to the user list of each site.

## The Issue:
The superadmin cannot access the dashboard. 

## Cause:
`$user->roles` is empty for users who are not members of a site.

## Fix:
There should be a special check for superadmins (as there is throughout core WordPress)

**Comment by jfarthing84** [comment]
Closing as likely irrelevant with 7+.
