### ISSUE TITLE
Available filter to remove password fields ?

### ISSUE THREAD

**Issue by Beee4life** [jfarthing84/theme-my-login#137]
I have tried to get an answer on the [WP forums](https://wordpress.org/support/topic/filter-available-to-add-placeholders-for-passwords/) but since there is no reply, I'm trying it here.

I'ld like to remove the password fields with a filter/action. Is this possible because now I have to 'hack' into the core plugin which will be gone with next update.

**Comment by jfarthing84** [comment]
I will answer on WP forums.
