### ISSUE TITLE
$this->is_active not reached

### ISSUE THREAD

**Issue by Beee4life** [jfarthing84/theme-my-login#138]
Taken from [WP forums](https://wordpress.org/support/topic/this-is_active-not-reached/) because I can't get a reply there, so trying it here.

I tried to register a user with twentyseventeen template active. It worked as expected.

I then switched to my custom theme. I then registered another user and noticed that $template->the_errors was not shown in my template.

After some debugging I noticed that this->is_active on line 209 from includes/class-theme-my-login-template.php is not passed. So $this is not active.

Any idea how to solve this ? I’d like to show error notices.

Note, I'm using Timber as a templating engine, which is a WP recognised plugin.

**Comment by jfarthing84** [comment]
I will respond in WP forums.
