### ISSUE TITLE
How to override message for action registration complete ?

### ISSUE THREAD

**Issue by Beee4life** [jfarthing84/theme-my-login#139]
How can I override the message for the action activation complete ?

    Your account has been activated. You may now log in.

Which is defined in user-moderation.php line 214.

    if ( isset( $_GET['activation'] ) ) {
        switch ( $_GET['activation'] ) {
            case 'complete' :
                if ( class_exists( 'Theme_My_Login_Custom_Passwords' ) )
                    $theme_my_login->errors->add( 'activation_complete', __( 'Your account has been activated. You may now log in.', 'theme-my-login' ), 'message' );
                else
                    $theme_my_login->errors->add( 'activation_complete', __( 'Your account has been activated. Please check your e-mail for your password.', 'theme-my-login' ), 'message' );
                break;
            case 'invalidkey' :
                $theme_my_login->errors->add( 'invalid_key', __( '<strong>ERROR</strong>: Sorry, that key does not appear to be valid.', 'theme-my-login' ) );
                break;
        }
    }

**Comment by jfarthing84** [comment]
This is not a bug.

**Comment by Beee4life** [comment]
I didn't say it was :) but as you know I was trying to get responses for quite a while (for which I now know why it took so long) so posted it here. Want me to re-post this on WP Forums ?

**Comment by jfarthing84** [comment]
If you still need help, you can.

**Comment by Beee4life** [comment]
I do ;)

**Comment by Beee4life** [comment]
See https://wordpress.org/support/topic/override-message-for-action-complete/
