### ISSUE TITLE
Undefined variable (and typo)

### ISSUE THREAD

**Issue by Beee4life** [jfarthing84/theme-my-login#145]
There's an undefined variable on line 331 in [class-theme-my-login.php](https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login.php#L331).

Which is also a typo since (afaik) it's referrer.

![screen shot 2018-02-20 at 12 31 37](https://user-images.githubusercontent.com/4508731/36447923-247428ea-1686-11e8-93db-39592bf328e5.png)

**Comment by jfarthing84** [comment]
> The HTTP referer (originally a misspelling of referrer[1]) is an HTTP header field that identifies the address of the webpage (i.e. the URI or IRI) that linked to the resource being requested. By checking the referrer, the new webpage can see where the request originated.
