### ISSUE TITLE
email address as user name bug

### ISSUE THREAD

**Issue by mcaravaglia** [jfarthing84/theme-my-login#146]
I have been using your login application on my website for a number of years, but just recently discovered a problem. A certain percent of our users create an account with their email address as their User Name. These users cannot use the "Reset Password" link to reset their password, as they will get an error message saying the "password reset link is invalid".  I receive emails from these users and I need to manually reset their password. Today I did some testing and confirmed that an email address as a User Name will not receive a usable link for to reset a password; I believe it is due to the "@" sign, as this symbol cannot be used in a URL.

I have two options; either I add code that prohibits the user from using an email address as their User Name, and also restrict the @ symbol, or see if there is an easier suggestion that (hopefully) you can provide?

**Comment by jfarthing84** [comment]
This is not the case as the email addresses are encoded using `rawurlencode`, so that the @ sign can be included. This is the exact same way the WP core handles it. Furthermore, I just tested and it worked flawlessly. There may be something else at play with your install.
