### ISSUE TITLE
Wordfence Conflict

### ISSUE THREAD

**Issue by EatonZ** [jfarthing84/theme-my-login#148]
When using this plugin with a site that utilizes Wordfence, the following error occurs when clicking the "Click here to unlock your ability to sign-in and to access to the site. Do this if you simply need to regain access because you were accidentally locked out." link in the unlock email you can receive when resetting your password too many times.

```
PHP Fatal error:  Uncaught Error: Call to a member function get_page_permastruct() on null in C:\wp-includes\link-template.php:357
Stack trace:
#0 C:\wp-includes\link-template.php(320): _get_page_link(Object(WP_Post), false, false)
#1 C:\wp-includes\link-template.php(144): get_page_link(Object(WP_Post), false, false)
#2 C:\wp-content\plugins\theme-my-login\includes\class-theme-my-login.php(954): get_permalink(Object(WP_Post))
#3 C:\wp-content\plugins\theme-my-login\includes\class-theme-my-login.php(690): Theme_My_Login::get_page_link('login', Array)
#4 C:\wp-includes\class-wp-hook.php(288): Theme_My_Login->site_url('https://...', 'wp-login.php', 'login')
#5 C:\wp-includes\plugin.php(203): WP_Hook->apply_filters('https://...', Array)
#6 C:\wp-includes\link-template.php(3036): apply_filters('site_url', 'https://...', 'wp-login. in C:\wp-includes\link-template.php on line 357
```

This is consistently reproducible, so let me know how I can help narrow this down further.

**Comment by jfarthing84** [comment]
Looks like another instance of a plugin that calls `wp_login_url()` before `$wp_rewrite` is constructed.

**Comment by EatonZ** [comment]
Anything you can do to fix?

I do have "Disable wp-login.php" checked as well.

**Comment by jfarthing84** [comment]
Not exactly. You could possibly apply a higher priority filter to `site_url` which skips attempting to fetch the page slug from the DB, if you know the links to your TML pages anyway.

**Comment by jfarthing84** [comment]
I suppose a fallback I could implement in this case would be to just use `wp-login.php`, but then if that's disabled, that's another problem. I suppose the next best solution would be to not use permalinks, if `WP_Rewrite` has not yet been instantiated.

**Comment by EatonZ** [comment]
Thanks so much for a quick fix. Just copied the changed file over and can confirm the crash no longer occurs.👍
