### ISSUE TITLE
General Plugin Issues

### ISSUE THREAD

**Issue by Eifee69** [jfarthing84/theme-my-login#15]
Hi,

Still having the same problems as before unfortunately. (BETA V2)

1.If I choose NOT to allow password creation , the password that is emailed does not work when entered.
1. If I select "Enable Custom Passwords" , when they set up the password and hit register , they have to put in their login details again , then once the ht login they are redirected "to my home page" , which I have selected in redirect , they then seem to be looged out. However if they follow the link that comes in the email which directs them to http://www.aberdeenpropertyshop.com/login-or-register/ , if they log in there then all is good and the redirection works.

Can you help please , is there a way to keep all logins to
http://www.aberdeenpropertyshop.com/login-or-register/ and remove the page it goes to after they hit register , after they select their password.

I know it may be a bit confusing , but if you could goto Aberdeenpropertyshop.com and create an account you will see what I mean.

Really like this plugin and really want it to work for me and hope my input helps.

Thanks
Eiffee

**Comment by jfarthing84** [comment]
There should be no password emailed. The new version sends them a link to set their own password.

**Comment by Eifee69** [comment]
Hi , thanks for the response. What variable should I put in the "New user" message part so they get the new password?. If I leave this part blank they get just an email with no content ,

Also can you look at my other questions.

If I select "Enable Custom Passwords" , when they set up the password and hit register , they have to put in their login details again , then once the ht login they are redirected "to my home page" , which I have selected in redirect , they then seem to be looged out. However if they follow the link that comes in the email which directs them to http://www.aberdeenpropertyshop.com/login-or-register/ , if they log in there then all is good and the redirection work

Thank you

**Comment by jfarthing84** [comment]
That's how registration works. You first register, and then you have to login. You aren't auto-logged in upon registration.

**Comment by Eifee69** [comment]
Hi. Sorry , but it's not working. Please can you sign up at www.Aberdeenpropertyshop.com and see want I mean. I can also send you a admin account if it helps. Can't figure it out.

Thanks
Eiffee.

**Comment by jfarthing84** [comment]
This is not the proper place for support.

**Comment by Eifee69** [comment]
So where is the proper place for support ??

**Comment by jfarthing84** [comment]
You've already posted at the proper place for support: https://wordpress.org/support/plugin/theme-my-login

**Comment by Eifee69** [comment]
Thanks. I think I will find an alternative as you don't seem to be able answer my questions. Thanks anyway and hope you get it fixed one day.
