### ISSUE TITLE
Removing Re-type password (pass2)

### ISSUE THREAD

**Issue by multiplehats** [jfarthing84/theme-my-login#154]
Hey! Great plugin.

This is my last resort. 

I can't find out for the life of me how to remove the second password field. Right now I did a hot-fix by editing the plugin  `public function password_errors` directly.

is there an appropriate filter so that I can remove the password field and it's validation? 

```
remove_action( 'register_form', array( Theme_My_Login_Custom_Passwords::get_object(), 'password_fields' ) );
/**
 * Remove plugin password fields and allow 1 password registration
 *
 *
 * @see Theme_My_Login::display()
 * @since 6.0
 * @access public
 */
function new_password_fields() {
  $template = Theme_My_Login::get_object()->get_active_instance();
  ?>
  <p class="tml-user-pass1-wrap">
    <label for="pass1<?php $template->the_instance(); ?>"><?php _e( 'Password', 'theme-my-login' ); ?></label>
    <input autocomplete="off" name="pass1" id="pass1<?php $template->the_instance(); ?>" class="input w-input" size="20" value="" placeholder="Password" type="password" />
  </p>

  <?php
}
add_action( 'register_form', 'new_password_fields', 5 );
```

I tried this, but the WP Error object is still checking for the second password field.

Any help is appreciated.

**Comment by RichardCoffee** [comment]
The WP Error object is being triggered with the $errors->add calls in the public function password_errors, in the same class.  I would suggest that replacing that function in a similar manner will solve your problem.  Simply remove/edit the parts referring to 'pass2'.

Personally, I would not have wanted to remove the second field.  It exists as a security cross check for the user's benefit.  You may want to revisit the logic requiring it's removal.

**Comment by multiplehats** [comment]
Yeah noticed it's in the same class unfortunately. But yes, edited references to pass2 and works as expected now. 

I understand the risk. Thanks for the follow up @RichardCoffee

**Comment by RichardCoffee** [comment]
Glad you were able to get it sorted out. :)
