### ISSUE TITLE
Test Cookie Set on Every Page Load

### ISSUE THREAD

**Issue by unixtam** [jfarthing84/theme-my-login#156]
Hi,

WordPress sets the test cookie when the login page is visited. TML currently sets a test cookie on every page load via the `template_redirect` hook, regardless of whether or not it's a TML page or TML related request (see `class-theme-my-login.php`, from line 330).

Besides setting a cookie that is unnecessary for many website visitors, this behavior may have implications for a website owner's privacy policy. The new WP privacy policy guide (`/wp-admin/tools.php?wp-privacy-policy-guide`) states `If you have an account and you log in to this site, we will set a temporary cookie to determine if your browser accepts cookies. This cookie contains no personal data and is discarded when you close your browser.` Admins that use TML would have to make changes to this point, which is not obvious.

I would suggest setting the test cookie more selectively, preferably in line with the text suggested by the WP privacy policy guide.

**Comment by jfarthing84** [comment]
I suppose I could attempt to set the cookie on the first login post. This will effectively take 2 failures to notify the user that they can't log in because cookies are blocked - but I suppose that is acceptable.

**Comment by unixtam** [comment]
That would come at the cost of usability. How about setting the cookie on a GET request for a page that contains a TML login form? That's how WP does it when users visit `wp-login.php`. (The privacy policy guide should probably be updated to more closely reflect what WP is actually doing.)

**Comment by jfarthing84** [comment]
It looks like really the only feasible way would be to set the test cookie if currently viewing a TML page or the widget is active.

**Comment by jfarthing84** [comment]
BTW, WP sets the test cookie upon visiting wp-login.php, regardless of the action.

**Comment by jfarthing84** [comment]
Come to think of it, the shortcode would also have to be accounted for. I'm not sure there's a way to cover 100% usage of it.

**Comment by jfarthing84** [comment]
Here's what I'm thinking:

```
$set_test_cookie = false;
if ( self::is_tml_page() ) {
	$set_test_cookie = true;
} elseif ( is_active_widget( false, false, 'theme-my-login' ) ) {
	$set_test_cookie = true;
} elseif ( is_singular() && has_shortcode( get_the_content(), 'theme-my-login' ) ) {
	$set_test_cookie = true;
}
$set_test_cookie = (bool) apply_filters( 'tml_set_test_cookie', $set_test_cookie );

if ( $set_test_cookie ) {
	// Set a cookie now to see if they are supported by the browser.
	$secure = ( 'https' === parse_url( wp_login_url(), PHP_URL_SCHEME ) );
	if ( ! isset( $_COOKIE[ TEST_COOKIE ] ) ) {
		setcookie( TEST_COOKIE, 'WP Cookie check', 0, COOKIEPATH, COOKIE_DOMAIN, $secure 
		if ( SITECOOKIEPATH != COOKIEPATH ) {
			setcookie( TEST_COOKIE, 'WP Cookie check', 0, SITECOOKIEPATH, COOKIE_DOMAIN, $secure );
		}
	}
}
```

This will set the cookie if viewing a TML page, the widget is present or viewing a single post/page with the shortcode in it's content. Additionally, provide a filter to allow other circumstances to be defined for edge cases.

**Comment by unixtam** [comment]
Looks good to me. However, the WP core team seems to favor the idea of changing the cookie behavior to be more in line with the text rather than the other way around. For the time being (aiming for 6.9.7), the text is going to be changed, but that may be reverted when (if) the behavior is changed, possibly in the next major release.

If the cookie was set upon successfully logging in, it would be available on the subsequent redirect in order to redirect back again and render the cookie error message. Unless I'm missing something, there should be a way to make this work without a second login attempt.

**Comment by jfarthing84** [comment]
If the cookie is set when the form is posted, when you enter the proper credentials with cookies turned on, you will still get the test cookie error on your first try because the cookie isn't available until the next request.
