### ISSUE TITLE
Login page doesn't accept any url parameter which makes it incompatible with wpml

### ISSUE THREAD

**Issue by nikhere1** [jfarthing84/theme-my-login#158]
#The plugin is great, but it has a huge issue, https://mywebsite.com/login?lang=en redirect me back to https://mywebsite.com/login/, i.e it automatically removes the query parameter, there are many requests on the wpml forums to fix this issue, https://wpml.org/forums/topic/registration-in-theme-my-login-links-to-login-page-multilanguage-site/

Just in case you are unaware of this issue, thanks for the plugin, cheers !!

**Comment by jfarthing84** [comment]
Hi @nikhilnagpal123,

Thanks for your report. Unfortunately, this is not the case for me. I can append any query argument to any TML page, including `lang` and it will still be there when the page loads. Have you tried disabling other plugins?

Additionally, the feature added in 6.4.13 where you can easily assign TML actions to pages via a meta box in the Pages admin should help mitigate some of the WPML issues.

**Comment by nikhere1** [comment]
Thanks for your quick response, I deactivated wpml and tried again, actually, then I can append the query argument `lang=en` to the login page, but it doesn't work with wpml, I will try to fix this issue, and update you soon, thanks!

**Comment by nikhere1** [comment]
Hi, I couldn't able to find the proper solution, but if I change the English login page URL from `https://mywebsite/login?lang=en` to `https://mywebsite/signin?lang=en`  then it doesn't redirect it back to `https://mywebsite/login/` but then there are few other issues, it shows an unnecessary message at the top. and  lost password page still needs to be translated, I know it is not fully compatible with wpml, but I really like this plugin,  but I think I have to switch to another wpml compatible plugin (like clean login) in future, Thanks
