### ISSUE TITLE
Getting error on includes

### ISSUE THREAD

**Issue by jamiekeefer** [jfarthing84/theme-my-login#16]
Warning: require_once(/home2/jbkeefer/public_html/txtdir.com/wp-content/plugins/theme-my-login/includes/class-theme-my-login-common.php): failed to open stream: No such file or directory in /home2/jbkeefer/public_html/txtdir.com/wp-content/plugins/theme-my-login-6.4-beta2/theme-my-login.php on line 18

Fatal error: require_once(): Failed opening required '/home2/jbkeefer/public_html/txtdir.com/wp-content/plugins/theme-my-login/includes/class-theme-my-login-common.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home2/jbkeefer/public_html/txtdir.com/wp-content/plugins/theme-my-login-6.4-beta2/theme-my-login.php on line 18

Line 18 is:

require_once( WP_PLUGIN_DIR . '/theme-my-login/includes/class-theme-my-login-common.php' );

I suspect the following require_once will fail as well.  The files are there,

The path is wrong because the ZIP folder is \theme-my-login-6.4-beta2.zip.

Just a heads up for people trying to use your link to download from github

Edited line 18 through 22 for successful install:

// Require a few needed files
require_once( WP_PLUGIN_DIR . '/theme-my-login-6.4-beta2/includes/class-theme-my-login-common.php' );
require_once( WP_PLUGIN_DIR . '/theme-my-login-6.4-beta2/class-theme-my-login-abstract.php' );
require_once( WP_PLUGIN_DIR . '/theme-my-login-6.4-beta2/class-theme-my-login.php' );
require_once( WP_PLUGIN_DIR . '/theme-my-login-6.4-beta2/class-theme-my-login-template.php' );
require_once( WP_PLUGIN_DIR . '/theme-my-login-6.4-beta2/class-theme-my-login-widget.php' );

for whatever reason simply changing the directory name to theme-my-login did not work.

**Comment by jfarthing84** [comment]
Make sure you first delete or rename the existing "theme-my-login" folder, if it exists. Then, rename the extracted folder to "theme-my-login".

**Comment by jamiekeefer** [comment]
using that method when I activate I get error: Plugin file does not exist.

**Comment by jamiekeefer** [comment]
I stand corrected its working now.  Thank you.
