### ISSUE TITLE
Not displaying

### ISSUE THREAD

**Issue by Tvhawk** [jfarthing84/theme-my-login#161]
Login form shortcode not displaying login form

**Comment by jfarthing84** [comment]
I believe this was fixed in 51f622b98be8b9bf661114394b9b899c0a337d54. Feel free to reopen if 7.0.2 doesn't resolve the issue.

**Comment by fourwhitesocks** [comment]
Please for the love of God REMOVE me from this thread, I have removed
myself about 8 times and did the same on Github and I'm still getting
these; please and thank you!!!

Please unsubscribe me:  Amy  and email is:  asbilly92@gmail.com

**Comment by jfarthing84** [comment]
@fourwhitesocks I don't see you as a watcher or having starred the repo. And even if I did, I couldn't remove you. You have to do that yourself.
