### ISSUE TITLE
Remove 'indicator_hint' error

### ISSUE THREAD

**Issue by rpf5573** [jfarthing84/theme-my-login#162]
1. remove indicator_hint field in register form on init hook.
2. loop tml_get_forms() -> tml_get_form_fields()
3. error

`Call to a member function render() on boolean - /Applications/MAMP/htdocs/wordpress/wp-content/plugins/theme-my-login/includes/class-theme-my-login-form.php:569 
#11 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/theme-my-login/includes/shortcodes.php:60 - Theme_My_Login_Form->render(Array[6])
#10 /Applications/MAMP/htdocs/wordpress/wp-includes/shortcodes.php:319 - tml_shortcode(Array[3], '', 'theme-my-login...')
#9 [internal call] - do_shortcode_tag(Array[7])
#8 /Applications/MAMP/htdocs/wordpress/wp-includes/shortcodes.php:197 - preg_replace_callback('/\\[(\\[?)(the...', 'do_shortcode_t...', '[theme-my-logi...')
#7 /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php:286 - do_shortcode('[theme-my-logi...')
#6 /Applications/MAMP/htdocs/wordpress/wp-includes/plugin.php:203 - WP_Hook->apply_filters('[theme-my-logi...', Array[1])
#5 /Applications/MAMP/htdocs/wordpress/wp-includes/post-template.php:240 - apply_filters('the_content', '[theme-my-logi...')
#4 /Applications/MAMP/htdocs/wordpress/wp-content/themes/alpool/page.php:20 - the_content()
#3 /Applications/MAMP/htdocs/wordpress/wp-includes/template-loader.php:74 - include('/Applications/...')
#2 /Applications/MAMP/htdocs/wordpress/wp-blog-header.php:19 - require_once('/Applications/...')
#1 /Applications/MAMP/htdocs/wordpress/index.php:17 - require('/Applications/...')`

How to remove some field properly?

Check please!

**Comment by jfarthing84** [comment]
How did you remove the field?

**Comment by jfarthing84** [comment]
Assuming this was fixed in 2ffb46cc6b2995a486b96d4562754bac71a0c26a.
