### ISSUE TITLE
Plugin update - form disappears!

### ISSUE THREAD

**Issue by abbeyrosekroll** [jfarthing84/theme-my-login#163]
Hi there, I've just updated this plugin on my clients website and now the login forms to get to WordPress have completely disappeared..am I the only one?!

**Comment by jfarthing84** [comment]
If you are using the widget to display these forms on the actual TML pages, please use the shortcode instead. The widgets no longer display on TML pages.

Additionally, the proper channel for support is here: https://wordpress.org/support/plugin/theme-my-login
