### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by romtonian** [jfarthing84/theme-my-login#165]
Good day,
Is anyone else getting the following error when they register?
ERROR: Please enter your first name.
ERROR: Please enter your last name.
ERROR: Please enter your phone number.
ERROR: Please enter your company name.
ERROR: Please enter your position at your company.
ERROR: Please enter your mailing address.
ERROR: Please enter your city.
ERROR: Please enter your state/province.
ERROR: Please enter your postal/zip code.
ERROR: Please enter your country.

The registration form I am using is the default, and only has space for "Username" and "Email", however once i press submit, all of the above errors come up. 

Any advice?

Thank you

**Comment by jfarthing84** [comment]
You have another plugin or custom code that is expecting those fields.
