### ISSUE TITLE
When using with Groups plugin the login/logout page are blank

### ISSUE THREAD

**Issue by evdheuvel** [jfarthing84/theme-my-login#166]
Hello TML,

I'm using the Groups and Groups 404 Redirect plugin and would like to combine it with TML. I notice that when I activate both Groups and Theme My Login the login and logout pages are blank. They only show the title (I didn't check the other TML pages). As a workaround I created the respective pages manually and added the [theme-my-login] shortcode  (old school). Luckily this works. 

Software used:
TML 7.0.10
Groups 2.3.1 (by itthinx)
WordPress 4.9.8

I hope you can resolve this.

Cheers,

Erik

**Comment by jfarthing84** [comment]
Can you verify if this is still an issue?

**Comment by jfarthing84** [comment]
Closing due to no response from reporter.
