### ISSUE TITLE
have eror with theme my login

### ISSUE THREAD

**Issue by aaria2008** [jfarthing84/theme-my-login#168]
i have eror
**

> Fatal error: Call to undefined function get_user_locale() in C:\xampp\htdocs\ig3\wp-content\plugins\theme-my-login\admin\functions.php on line 132

**
in my locall host 
what should i do ? please help me :)
tnx

**Comment by aaria2008** [comment]
![functions](https://user-images.githubusercontent.com/42569978/44390650-0a5c1980-a543-11e8-9227-eae9f309bfe8.jpg)
the type of the file is not jpg .it is php

**Comment by jfarthing84** [comment]
You should seek support in the [support forum](https://wordpress.org/support/plugin/theme-my-login).

**Comment by aaria2008** [comment]
i fix it
