### ISSUE TITLE
Cannot confirm the password

### ISSUE THREAD

**Issue by unicornis-pl** [jfarthing84/theme-my-login#17]
I can enter the password, the strength indicator works fine. But when starting to type into the password confirmation field, it takes one or two characters and then erases the content of the confirm box, making it impossible to change the password.

Issue is only with WP 4.3.

**Comment by jfarthing84** [comment]
Are you using the beta? There should no longer be a password confirmation box in 6.4.

**Comment by unicornis-pl** [comment]
Beta 2 with custom php form - the same I was using in 6.3.12. 

How the password change should work w/o password confirmation box? I need to have a closer look to examine how the passwords work in 4.3. 
If you say there is no password confirmation box in 6.4, most likely I need to change custom form I was using with the previous version on plugin.

**Comment by jfarthing84** [comment]
You definitely need to update your custom form.

**Comment by unicornis-pl** [comment]
Thanks. If I set up the beta version of the plugin, will the settings stay when the final version is released? 
Can I install 6.4 beta w/o uninstalling 6.3.12 in order to preserve my settings or should I retype all of the once again?

**Comment by jfarthing84** [comment]
The settings API has not changed for 6.4. You should be fine. However, the same can probably not be said for 7.0.
