### ISSUE TITLE
Adding Field via Hook is not working?

### ISSUE THREAD

**Issue by codetycon** [jfarthing84/theme-my-login#170]
I am using hook to add more fields to form but the fields are not showing on Registration form,
Here is my code

`tml_add_form_field( 'register', 'first_name', array(
	'type' => 'text',
	'value' => tml_get_request_value( 'first_name', 'post' ),
	'label' => 'First Name',
	'description' => 'Enter your first name.',
	'priority' => 5,
) );
tml_add_form_field( 'register', 'custom', array(
	'type' => 'custom',
	'content' => 'The content of my custom form field.',
	'priority' => 5,
) );`

**Comment by jfarthing84** [comment]
Please use the [forums](https://wordpress.org/support/plugin/theme-my-login/) for support.
