### ISSUE TITLE
Enable cookies before login

### ISSUE THREAD

**Issue by parkcityguy** [jfarthing84/theme-my-login#172]
I got the error: You must enable cookies before login. They are enabled. When I try the second time, it all works fine. So, I’ve got errors at the first attempt, try again and success. 

If I log out and then log in the problem does not occur on that first attempt

I am running WordPress 5.1.1 with the Twenty Twelve theme My blog is blog.e-janco.com.

I see this was a problem last year and it was marked as resolved.  I cannot see anything on your site on how to fix this problem

**Comment by pbrocks** [comment]
@parkcityguy Is it possible that the first page view is non-SSL? I've seen this type of message happen on many WP sites without TML? In fact, I've seen it where just by changing the protocol, I find that I am logged in with SSL but not without.

**Comment by jfarthing84** [comment]
Closing due to no response from the reporter.
