### ISSUE TITLE
Login is not working 

### ISSUE THREAD

**Issue by BytelogicTech** [jfarthing84/theme-my-login#173]
Hi there, i am using Version 7.0.13 
i am facing a little challange, i am allowing user to enter his desired password at the time of registration. 
But i am wonder that password doesn't work after logged out and trying to login agin. I have to reset the password to login again.
My URL - http://jyoti.bytelogictech.com

Kindly look into it

**Comment by jfarthing84** [comment]
Does this still happen with TML 7.0.15? Have you tested with other plugins disabled?

**Comment by netzlodern-pats** [comment]
Hi there,

we are using the current version of the plugin and have the same problem.
Only Admin-Accounts seems to be affected though.

Browser console javascript error: “TypeError: a.data is undefined”.

As workaround we renamed the plugin folder to deactivate the plugin. But we need our styled login back.


Best regards

**Comment by jfarthing84** [comment]
Closing due to no response from reporter.
