### ISSUE TITLE
Invalid Key during password reset

### ISSUE THREAD

**Issue by pbrocks** [jfarthing84/theme-my-login#175]
First off, I should say that the site is hosted on WPEngine, which has a rather expansive caching, but when a user fills out the form on `/lostpassword` page, they go to their email to click the link and return. Upon arriving at  `/resetpassword` page, some users find that they get the error about an invalid key. Most do not. We've tried excluding everything from the cache and yet one or two a day are still happening. Any ideas what is causing this?

**Comment by jfarthing84** [comment]
I would ensure that they are really excluding all the proper paths. This is a caching issue 99% of the time.
