### ISSUE TITLE
"Welcome" tag can't be translated

### ISSUE THREAD

**Issue by GabrielHenriqueRS** [jfarthing84/theme-my-login#178]
I found a string that is not ready for i18n:
https://github.com/theme-my-login/theme-my-login/blob/a29b2f11ea1fbf9d39a0897da77720006e93fc7c/src/includes/class-theme-my-login-widget.php#L57
This is a crucial string because is an important information that is displayed directly for the user on login widget.

**Comment by jfarthing84** [comment]
The code you pasted literally shows the string as being ready for translation, using the `_x` function...

**Comment by jfarthing84** [comment]
Closing due to no response from reporter.
