### ISSUE TITLE
Disable /wp-admin redirect

### ISSUE THREAD

**Issue by sebastiande** [jfarthing84/theme-my-login#179]
Hi,

i setup Theme My Login and it works quite well, but now it also redirects all the admins from /wp-admin to the frontend login form. Is there an option to disable this and just use the original WP login form if I enter /wp-admin?

Thanks,
Sebastian

**Comment by jfarthing84** [comment]
No, and I don't understand why you would want to do so.

**Comment by sebastiande** [comment]
Cause the whole deeplinking isn't working anymore for the admins.
If I go for example to https://mydomain.de/wp-admin/plugins.php?plugin_status=all&paged=1&s 

I get redirected to the frontend login page of TML, if I'm not logged in, with the redirect_to query param (with double encoded value). If I now login in with correct details I get redirected to https://mydomain.de/tmlLoginPage/https%3A%2F%2Fmydomain.de%2Fwp-admin%2Fplugins.php%3Fplugin_status%3Dall%26paged%3D1%26s

which will result in 404.

**Comment by jfarthing84** [comment]
Maybe try this:

```
add_action( 'admin_init', function () {
    remove_filter( 'site_url', 'tml_filter_site_url' );
} );
```

**Comment by sebastiande** [comment]
Sorry forgot to add it. Thanks I removed the filter in general but you are right maybe it is better to remove it in the admin_init. Thanks!
