### ISSUE TITLE
Plugin conflict wp_nav_menu_item_custom_fields requires 5 parameters (Memberium)

### ISSUE THREAD

**Issue by Codex101** [jfarthing84/theme-my-login#180]
Hi,

Wordpress 5.4 can now allow 5 parameters for wp_nav_menu_item_custom_fields [doc](https://make.wordpress.org/core/2020/02/25/wordpress-5-4-introduces-new-hooks-to-add-custom-fields-to-menu-items/)

Wordpress: 5.4
Theme My Login: Version 7.0.15
Memberium: Version 2.161

Memberium wordpress plugin uses the 5 parameter variant and enforces 5 parameters. Thus this plugin breaks when navigating to Appearance >> Menu (In the wordpress admin dashboard)

In theme-my-login/admin/class-theme-my-login-walker-nav-menu-edit.php, changing line 42 

do_action( 'wp_nav_menu_item_custom_fields', $item->ID, $item, $depth, $args);

to 

do_action( 'wp_nav_menu_item_custom_fields', $item->ID, $item, $depth, $args, $id );

Fixes the Appearance >> Menu crash cause it's now using 5 parameters. 

Any chance you could update your plugin with this?

**Comment by jfarthing84** [comment]
Sorry, but this is already fixed in our development branch
