### ISSUE TITLE
 Can not log in

### ISSUE THREAD

**Issue by netzlodern-pats** [jfarthing84/theme-my-login#181]
Hi there,

we are using the current version (7.1) of the plugin and can't log in anymore.
All credentials are there, cache has been cleared but when hitting the login button, nothing happens.
Only Admin-Accounts seems to be affected though.

Browser console javascript error: “TypeError: a.data is undefined”.

As workaround we renamed the plugin folder to deactivate the plugin. But we need our styled login back.

Best regards

**Comment by jfarthing84** [comment]
Can you test with other plugins disabled and a default theme active?

**Comment by netzlodern-pats** [comment]
I tested a little further and found that the 2FA feature of iThemes Security Pro is causing the problem. As soon as I deactivate the 2FA function, the login works again. In our case 2FA is only enabled for admins, so other accounts can login.

Hope that helps.

**Comment by jfarthing84** [comment]
What about if you update TML to 7.1.1 and disable AJAX?

**Comment by netzlodern-pats** [comment]
The problem is no longer there.
