### ISSUE TITLE
[Fast Tweak] Add Support for Elementor

### ISSUE THREAD

**Issue by oagix** [jfarthing84/theme-my-login#182]
Add support for Elementor so that it doesn't crash when trying to edit a TML-selected page. 

`includes/actions.php`

Line 307, add:

```
if( isset( $_GET['elementor-preview'] ) ) {
	return;
}
```

**Comment by oagix** [comment]
@jfarthing84

**Comment by jfarthing84** [comment]
Does Elementor still crash with TML 7.1.1?

**Comment by jfarthing84** [comment]
Closing due to no response from the reporter.
