### ISSUE TITLE
Error: Options page not found.

### ISSUE THREAD

**Issue by voortmanc** [jfarthing84/theme-my-login#184]
When trying to save changes on the Theme My Login Settings page, I am getting the following error 'Error: Options page not found.' I am running a clean WordPress 5.5 in multisite environment.

Software used:
WordPress 5.5
Theme My Login 7.1.1
No other active or installed plugins

**Comment by jfarthing84** [comment]
Fixed in 805ef6e988a2a68273077a3ad9927b9ce83a16e7.
