### ISSUE TITLE
How to get the current action/page on a template?

### ISSUE THREAD

**Issue by ahmu83** [jfarthing84/theme-my-login#188]
Is there a way to get the current action on a template file. I have theme-my-login.php added to my theme to render all the pages and I am trying to get the current action on this template. Is there a way to do this? i.e, is it profile page, dashboard page etc

**Comment by jfarthing84** [comment]
You want [tml_get_action()](https://github.com/theme-my-login/theme-my-login/blob/a0100bf596e0f7b60e87a556b40a7c3bc485f6cd/src/includes/actions.php#L133). It returns a TML_Action object, which you would then call get_name() on. Like so:

```
if ( $action = tml_get_action() ) {
    if ( 'register' == $action->get_name() ) {
        // Do something
    }
}
```

Also, this is not a support form. Please direct these kind of requests [here](https://wordpress.org/support/plugin/theme-my-login/).
