### ISSUE TITLE
New password is not shown

### ISSUE THREAD

**Issue by Beee4life** [jfarthing84/theme-my-login#20]
I am playing around with 6.4-beta2.

I made a (new) copy of the profile-form.php and was editing the layout.
I clicked the change password but I didn't see a new generated password (which you do see when going to wp-admin/profile.php.

I clicked show/hide several times but nothing changed. In this screenshot the password should be shown, because the button says hide. When you click hide the password gets selected and is not shown as it should be, but when then clicking show, doesn't reveal the password.

See screenshot.

![150913-tml-no-password](https://cloud.githubusercontent.com/assets/4508731/9835169/0742b484-59dd-11e5-834e-76fac06fe1fb.png)

**Comment by jfarthing84** [comment]
It works for me. Try it with a complete vanilla installation of TML and a default theme.

**Comment by Beee4life** [comment]
tested it on clean install and it works there indeed...

any idea what could cause this 'error' ???

**Comment by jfarthing84** [comment]
Clearly it's either another plugin or the theme you were using...

**Comment by Beee4life** [comment]
I don't dispute that... but seeing as I have a lot of plugins was hoping you might have a clue where to point me ;)

**Comment by Beee4life** [comment]
just deactivated all plugins but TML and still occurs, so it's theme related... Seeing as I use a custom theme I have some digging to do I think....

**Comment by Beee4life** [comment]
I found the culprit.... thought I post it for others who might experience this.

it seemed I still had 'old' css which belonged to the previous version, related to the fix with the passwords.

I had this in my css
`input#pass1-text { display: none; }`
which caused the new password field to be hidden.

Also in the new css this is 'new', which I didn't add (yet).
`.show-password #pass1 { display: none; }`
After correcting it, it all seems to work as it should.
