### ISSUE TITLE
redirect to backend cannot be changed when login form is loaded directly

### ISSUE THREAD

**Issue by cherbst** [jfarthing84/theme-my-login#201]
The commit https://github.com/theme-my-login/theme-my-login/commit/40ccc0d2bdbaadb171f36f762d3fee3e418b0372  changed the behavior of TML so that after a direct call of the login page, after login, the user is redirected to the backend instead of the URL which is returned by the filter `login_redirect`

This is a regression. Please revert the commit.

**Comment by jfarthing84** [comment]
The `login_redirect` filter is still applied [just before the redirect takes place](https://github.com/theme-my-login/theme-my-login/blob/ef2163b93d1a21257076a0f36d137c647e7fe400/src/includes/actions.php#L452).
