### ISSUE TITLE
Single quote in password on registration results in failing login

### ISSUE THREAD

**Issue by Connum** [jfarthing84/theme-my-login#202]
There is an issue in the function `tml_set_new_user_password()` that results in a user registering with a password that contains a single slash not being able to log in after registration. The reason is that WordPress uses the slashed password string to generate the password hash, but `tml_get_request_value()` is used here to retreive the password, which internally applies `wp_unslash()`.

This is the fix I'm using for now, but it should be fixed in the original function:

```php
remove_action( 'register_new_user', 'tml_set_new_user_password' );
add_action( 'register_new_user', 'fix_tml_set_new_user_password' );
function fix_tml_set_new_user_password( $user_id ) {
	if ( ! tml_allow_user_passwords() ) {
		return;
	}

	if ( ! $password = wp_slash( tml_get_request_value( 'user_pass1', 'post' ) ) ) {
		return;
	}

	wp_set_password( $password, $user_id );
	update_user_option( $user_id, 'default_password_nag', false, true );
	
	if ( tml_allow_auto_login() ) {
		wp_set_auth_cookie( $user_id );
	}
}
```

**Comment by jfarthing84** [comment]
I am unable to reproduce this. Which WP version, and more importantly, PHP version, is this occurring on?

**Comment by Connum** [comment]
WordPress 5.9.3 on PHP 7.4.27

**Comment by jfarthing84** [comment]
Though I can't reproduce, I see no reason to avoid using tml_get_request_value() here, and instead use the raw $_POST value.
