### ISSUE TITLE
Allow "remember me" after auto login

### ISSUE THREAD

**Issue by EatonZ** [jfarthing84/theme-my-login#205]
Are you able to add an option to enable "remember me" after auto login?
It is very simple and you just have to set the remember param to true [here](https://github.com/theme-my-login/theme-my-login/blob/26704522ac92ac3e5ddf73e6168769ca56db3e5f/src/includes/functions.php#L855) for [wp_set_auth_cookie](https://developer.wordpress.org/reference/functions/wp_set_auth_cookie/).

**Comment by jfarthing84** [comment]
You can just use the [auth_cookie_expiration](https://developer.wordpress.org/reference/hooks/auth_cookie_expiration/) filter for that.
