### ISSUE TITLE
Plugin not compatible with 2FA

### ISSUE THREAD

**Issue by nigelthurlow** [jfarthing84/theme-my-login#206]
Using Wordfence, but also tested with other 2FA providers, this plugin causes lockout from the WP site. It also prevents Wordfence captcha from working. This is an issue as 2FA is essential for admins and cannot be enabled. 

Wordfence known issue log

Description: When our CAPTCHA feature is enabled users can’t log in and the default WordPress login error, or our “Don’t let WordPress reveal valid users in login errors” option error, is not displayed.

If at least one user has our two-factor authentication enabled then the default WordPress login error, or our “Don’t let WordPress reveal valid users in login errors” option error, is not displayed.

If at least one user has our two-factor authentication enabled and another user that does not have our two-factor authentication enabled tries to log in then they will not be able to log in.

If a user has our two-factor authentication enabled they can log in with their username and password to generate the two-factor authentication code submission form, but they will not be able to log in when entering the two-factor authentication code.

**Comment by jfarthing84** [comment]
These plugins are most likely unaware of TML at all. We offer our own 2FA extension, and you can always fallback to /wp-login.php.
