### ISSUE TITLE
Lost password showing critical error

### ISSUE THREAD

**Issue by atifishaq** [jfarthing84/theme-my-login#208]
![reset pss](https://github.com/theme-my-login/theme-my-login/assets/15226563/25e69dd2-4478-4b61-8efa-849da2e1dfd0)

On reset password i am getting error, can you please fix this asap... nd in old version its showing validation key is invalid

**Comment by jfarthing84** [comment]
What WP version is this?

**Comment by atifishaq** [comment]
Yes its WP

**Comment by jfarthing84** [comment]
Closing due to no response from reporter.
