### ISSUE TITLE
PHP 8.1 deprecation

### ISSUE THREAD

**Issue by ikender** [jfarthing84/theme-my-login#209]
Deprecated: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in /site/wp-content/plugins/theme-my-login/includes/class-theme-my-login.php on line 745

This one is less specific, but TML is the only plugin using wp_no_robots() that I found in my grep search
Deprecated: Function wp_no_robots is deprecated since version 5.7.0! Use wp_robots_no_robots() instead. in /site/wp-includes/functions.php on line 6031

**Comment by jfarthing84** [comment]
You are clearly using the 6.4.x branch, which is no longer supported.
