### ISSUE TITLE
Reset password dialog accepts weak passwords

### ISSUE THREAD

**Issue by unicornis-pl** [jfarthing84/theme-my-login#21]
Reset password dialog accepts even single character passwords.

Jeff, would you be so kind and answer my question regarding password strength meter on a registration page (see the question from yesterday, marked closed)?
I cannot also figure out how to block weak passwords on a registration page - the strenght meter works fine, but I do not know how to link waek passwords with disabling the Register button.

**Comment by jfarthing84** [comment]
The thing is, this is the exact same way that WordPress core works. It allows you to set even a one character password, even though the whole aim of the password UI redesign was to encourage more secure passwords. I guess they figured the "Accept weak password" checkbox warranted allowing such seriously weak passwords. I suggest you file a bug report with WordPress core.
