### ISSUE TITLE
Can't Redifine Password

### ISSUE THREAD

**Issue by alexmigf** [jfarthing84/theme-my-login#23]
I'm facing a problem after WP update 4.3, and this problem persist in Beta.

I type the password in the first field, but when i type the re-type field the first one goes blank.

Do you know what's going on?

**Comment by alexmigf** [comment]
Solution here https://wordpress.org/support/topic/reset-password-email-with-expired-key

**Comment by jfarthing84** [comment]
The solution is the release candidate. There's no second field when javascript is turned on and TML's stylesheet is loaded.
