### ISSUE TITLE
/lostpassword/?error=invalidkey

### ISSUE THREAD

**Issue by mywhitec** [jfarthing84/theme-my-login#24]
Hi. I've updated to beta 6.4, but still experiencing invalid key issue when trying to reset password.

**Comment by jfarthing84** [comment]
And did you see [this](https://wordpress.org/support/topic/password-reset-issues-3)?

**Comment by mywhitec** [comment]
Hi

Thanks for the reply. Turns out SB welcome emails and tml are no longer compatible I think due to this reset password change inwordpress 4.3 although SB welcome is updated to 4.3

Thanks
