### ISSUE TITLE
Profile form - Password

### ISSUE THREAD

**Issue by acarpio89** [jfarthing84/theme-my-login#25]
Hi Jeff

Thank you for quickly releasing a new version to address the problems caused after upgrading WordPress to 4.3. The password reset issue has been fixed now. However, I'm still having issues when a user tries to change his password once logged in.

Typing inside the "confirm password" field deletes what the user had previously typed in the "new password" field, making it impossible to submit this form correctly and changing the password. I can see the following error on the JS console whenever I type inside the "confirm password" field:

user-profile.min.js?ver=4.3:1 Uncaught TypeError: Cannot read property 'className' of undefined

**Comment by adamhurlebaus** [comment]
With the new update there should not be a confirm password field.  Is it possible you have overridden one of the template files by adding it to your theme?

It might be a plugin conflict as well - does this thread help you at all? - https://github.com/jfarthing84/theme-my-login/issues/14

**Comment by acarpio89** [comment]
You're right. The problem is that the templates are overridden in the theme. Thanks mate

**Comment by ohsik** [comment]
@acarpio89 
I'm having the same issue on my custom theme and noticed it works find on Twenty Fifteen theme.
Would you mind explain me what you meant by `the templates are overridden in the theme`?

**Comment by acarpio89** [comment]
There are a few template files under theme-my-login/templates.. for example: profile-form.php

My theme also has a file named profile-form.php, which is used to show a custom form to update the user profile instead of the one that comes with the plugin. This means that I need to copy the fixes included in the new version of the plugin's profile-form.php into my profile-form.php

**Comment by ohsik** [comment]
Thank you so much! now I see the `profile-form.php` that I added to remove the toolbar option lol

**Comment by adamhurlebaus** [comment]
Glad to help!
