### ISSUE TITLE
Login/Logout menu item is hidden

### ISSUE THREAD

**Issue by philippeAPB** [jfarthing84/theme-my-login#26]
Hi,
I guess there is an issue with wp_setup_nav_menu_item function in class-theme-my-login.php line 783.
The Login item menu is made invalid rather than being set to Log Out, as it was in the previous version.
So if you plan to deal with login/logout in a custom menu, since you are logged, there is no way to logout by menu.
best regards
Philippe

**Comment by jfarthing84** [comment]
No, you also add the Log Out page to your menu. Log In will be hidden when logged in and Log Out will show and vice-versa when not logged in.

**Comment by philippeAPB** [comment]
Thanks for your reply.

Ok that’s very clear now !

Thanks again for your plugin. Very nice job

Phil

```
  115 Rue C. Nicolas Ledoux - Hémiris B - 13 854 Aix-en-Provence
  Cell. 06 33 87 22 74 - Tél. 04 42 20 22 68 
  contact@applibiz.com <mailto:contact@applibiz.com> 
  Facebook <http://www.facebook.com/applibiz> | Twitter <http://twitter.com/@applibiz> | www.applibiz.com <http://www.applibiz.com/> 
```
