### ISSUE TITLE
Referer redirect setting sends user back to Password Reset page when logging in after reset

### ISSUE THREAD

**Issue by jfarthing84** [jfarthing84/theme-my-login#28]
When a use registers, they are sent a link to reset their password. After they (re)set their password, they will more than likely log in. However, if the Custom Redirection module is active and set to "Referer" for the login redirect for their role, they will be sent back to the Reset Password page which will then forward them to the Lost Password page with the invalid key error.

**Comment by strattonn** [comment]
The bug is closed. Was there a code change for this that can be applied? I'm at version 6.4.

**Comment by jfarthing84** [comment]
Yep, 2cee1f5d1a5642679218c742b1543a50161635b2.
