### ISSUE TITLE
Email Verification link not working

### ISSUE THREAD

**Issue by pumamammal** [jfarthing84/theme-my-login#30]
Hello, thank you for creating a plugin like this>

Initial Problem
Each time a user creates an account, the link sent to the user to verify account redirects to a 404 page and the user is not still active. 

I got frustrated after 2days of trying to fix it. So i deleted Theme my login and all the pages it created itself. No I reinstalled it. It did readd those pages, 

Am so furstrated right now. is there anything you can help me with pleeeeeeeeeeeeeeeaaseeeeee..

**Comment by adamhurlebaus** [comment]
Are you using the most current version of Theme My Login?   

Go to your dashboard then to Settings » Permalinks. Selected something other than the default settings and save. Reload your page.  Any change?

You could also check to see if there is another plugin that is causing a conflict.

**Comment by jfarthing84** [comment]
A 404 sounds like a simple permalink issue. As mentioned above, refresh your permalinks.
