### ISSUE TITLE
layout problem

### ISSUE THREAD

**Issue by virusme** [jfarthing84/theme-my-login#32]
@jfarthing84, I am not sure if this should be posted here or elsewhere. Let me know if this is the wrong  forum for this.

I recently updated Theme My Login to the latest release and my login form layout does not like it, basically form layout gets stuffed. 
I reverted the version to a previous version and the form layout becomes fine! I am unable to figure out what aspect of the new release is messing with the form layout!

This is the form layout before the update: https://dl.dropboxusercontent.com/u/18871256/website/good_1.png

This is the form layout after the update:
https://dl.dropboxusercontent.com/u/18871256/website/error_1.png

**Comment by adamhurlebaus** [comment]
All template classes in version 6.4 were prefixed with "tml" (link: https://github.com/jfarthing84/theme-my-login/commit/9189b52a1c8e2aaaaadc2a6d48d9e9b7b2541a5a)

Is it possible that you themes style sheet was styling the login form with the old selectors?  If so, you could just modify the style sheet in your child theme to account for the newer selectors.

**Comment by jfarthing84** [comment]
As mentioned above, check your stylesheet for TML classes and adjust them appropriately.

**Comment by virusme** [comment]
thanks @adamhurlebaus  and @jfarthing84
