### ISSUE TITLE
Empty settings in modules

### ISSUE THREAD

**Issue by rollecode** [jfarthing84/theme-my-login#34]
Hi! I don't see anything in module settings. Latest version in use. What gives?

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screenshot%202015-12-07%2010.05.39.png)

**Comment by jfarthing84** [comment]
Must be another plugin. Try deactivating them one-at-a-time too see which one it is.

**Comment by rollecode** [comment]
Nope. Disabled everything except Theme My Login. Still empty.

**Comment by jfarthing84** [comment]
Tried a default theme as well?

**Comment by rollecode** [comment]
Oh well, didn't realise it could be theme specific. Maybe something wrong with the template files. Thanks for the tip and sorry for the sleep deprivation.

**Comment by jfarthing84** [comment]
It's possible a theme (incorrectly) loads some conflicting javascript or stylesheets within the admin area.

**Comment by rollecode** [comment]
It's not a javascript or styles issue, because the console is free of errors and as you can see in the screenshot, the HTML bit is empty as well. It's either something with the template functions, language textdomains (I have translated the plugin in Finnish) or caused by something else. Have to investigate...

**Comment by jfarthing84** [comment]
Somehow a script could be removing the contents. There wouldn't necessarily be an error.
