### ISSUE TITLE
force_ssl_login is deprecated since version 4.4

### ISSUE THREAD

**Issue by chuckreynolds** [jfarthing84/theme-my-login#35]
PHP error using query_monitor 
`force_ssl_login is deprecated since version 4.4! Use force_ssl_admin() instead.`
- https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login-template.php#L264
- https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login.php#L460
- https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login.php#L955

edit: just saw the 6.4 branch... updated links

**Comment by jfarthing84** [comment]
Fixed in 33dd511fa535d36c76cbd423df2a18986fbf63f2, c2a6f94cdcb4d131e0559b54b192b52bb2a7856d and 15df4894b03e33e83091b42be00e3965c3cd0a71.

**Comment by chuckreynolds** [comment]
:+1:
