### ISSUE TITLE
get_password_reset_key() function not available in WP < 4.4.0

### ISSUE THREAD

**Issue by achilles283** [jfarthing84/theme-my-login#39]
Theme My Login 6.4.1 reset password functionality returns 500 error on WP version 4.3.1:

PHP Fatal error:  Call to undefined function get_password_reset_key() in .../theme-my-login/includes/class-theme-my-login.php on line 1156

Looks like this function wasn't added to WP core until 4.4.

**Comment by asmaloney** [comment]
This explains why my server returned a 500 on lost password.

**Comment by jfarthing84** [comment]
I'll require WP 4.4+ in 6.4.3, which is now imminent.

**Comment by jfarthing84** [comment]
TML now requires 4.4+, as per 46a7ad666a936a15e872757c796e72830ec0e056.

**Comment by younes0** [comment]
What about users stick with WP 4.3 ?

**Comment by jfarthing84** [comment]
You'll need to downgrade TML to a compatible version, namely 6.4.

**Comment by younes0** [comment]
6.4.1 I guess? thanks!
