### ISSUE TITLE
GH default branch

### ISSUE THREAD

**Issue by jrfnl** [jfarthing84/theme-my-login#42]
Considering that development is done in the 6.4 branch, you may want to change the default branch from `master` to `6.4`.

Settings -> Branches -> Default branch

That way anyone visiting will actually see the real repository instead of the stub in master. Also new pull requests will then automatically be done against 6.4, instead of contributors having to manually change that for each PR.

**Comment by jfarthing84** [comment]
Didn't even know I could do that. Thanks!

FYI: 7.0 will be in master at some point.

**Comment by jrfnl** [comment]
You can always change it back towards that time ;-)
