### ISSUE TITLE
[6.4.2] New User email not being used

### ISSUE THREAD

**Issue by asmaloney** [jfarthing84/theme-my-login#43]
The TML **New User** email isn't being sent - the default WP one is.

I think this is since I updated to 6.4.2.  I plan to revert to 6.4.1 because of issue #39 anyways, so that will hopefully determine if it's an issue with 6.4.2...

(Edit:  WP v4.3.1)

**Comment by asmaloney** [comment]
Reverting to 6.4.1 fixed this issue and issue #39.

**Comment by ghost** [comment]
I too have the same problem ... reported just moments ago on the public WP support forums.

**Comment by jfarthing84** [comment]
Are you using the User Moderation module as well?

**Comment by asmaloney** [comment]
I am not.  I have the following active:
- Enable Custom E-mail
- Enable Custom Redirection
- Enable Themed Profiles

**Comment by jfarthing84** [comment]
WP version?

**Comment by jfarthing84** [comment]
There's the problem. You'll need to either upgrade WP to 4.4 or downgrade TML to 6.4.1.

**Comment by ghost** [comment]
I have the problem with WP 4.4 AND TML 6.4.2.  This closing is not satisfactory.

Oh... I see that you just opened #44 for this case.  I'll watch it. Thanks.

**Comment by jfarthing84** [comment]
@bobeaston Your issue is different. See #44.

**Comment by asmaloney** [comment]
I would expect a point release (6.4.1 to 6.4.2) to only be fixes and to maintain backwards compatibility.  (Upgrading to 4.4 is not a solution for all of us.)

**Comment by jfarthing84** [comment]
Then I would suggest downgrading TML to [6.4.1](https://downloads.wordpress.org/plugin/theme-my-login.6.4.1.zip).
