### ISSUE TITLE
6.4beta -- no registration mail being sent

### ISSUE THREAD

**Issue by robbyvillabona** [jfarthing84/theme-my-login#5]
I'm testing 6.4 beta with WP 4.3.  I've been testing registration and it only gets as far as activating the account (after clicking the activation link sent via email).  However no further email is sent containing the link where the newly registered user can set his password.

I also tried the "Lost password" form so I can trigger the sending of the email.  Any valid username or email address (even admin) entered always gives the message "Password reset is not allowed for this user".  The accounts I used are not locked out by Wordpress so that can't be it.  LMK what I can do to help debug.

**Comment by jfarthing84** [comment]
Do you have the Custom E-mail module enabled?

**Comment by robbyvillabona** [comment]
Yes, I did.  Anyway I tested my install with another alternative login program to isolate the source and I still had the same problem.  I just disabled all other plugins first to find out what was causing it and it turned out to be BulletProof Security.  Somehow disabling it then reenabling it seems to have fixed the problem.  Also the 6.4beta2 seemed to have fixed the email sending problem so you can consider this closed.  I might have some other issues to report but let me test further.  Thank you.
