### ISSUE TITLE
problem using TML

### ISSUE THREAD

**Issue by tnaoesting** [jfarthing84/theme-my-login#50]
Hello,
I have been trying to use Theme my login, but keep getting errors when I try to login or log out.  Of course, the problem disappears when I disable TML.  I have scoured the internet looking for a solution, and it seems that I have no way to point to the id of the login page in my settings.  However, this may be info that is outdated and for an older version of the plugin.  Here is the error:
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, cgiadmin@yourhostingaccount.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request."

I have tried uninstalling and reinstalling, various configurations and such, but I can't seem to make it work.  I am using "The7.3" theme on my site, www.classroomechanics.com .  Is there possibly some kind of theme incompatibility? Are there other settings in WP4.4 that need to be activated to make this work?  Might a W3 Total Cache setting be creating a problem?

**Comment by jfarthing84** [comment]
This is not the proper forum for support. That is at https://wordpress.org/support/plugin/theme-my-login.
