### ISSUE TITLE
TML and WPML

### ISSUE THREAD

**Issue by Colir** [jfarthing84/theme-my-login#52]
Hi.
i'm looking for a way to add some page to TML (is_tml_page() )
Actually my all website is locked to none logged user by this way

```
//SECURE ALL WEBSITE
function template_redirect() {
    if ( ! ( is_user_logged_in() || Theme_My_Login::is_tml_page() ) ) {
        $redirect_to = apply_filters( 'tml_security_private_site_redirect', wp_login_url( $_SERVER['REQUEST_URI'], true ) );
        wp_safe_redirect( $redirect_to );
        exit;
    }
}
add_action( 'template_redirect',  'template_redirect'  );
```

I use WPML.
My login page url is "/fr/login"
And i want to add login and forget page in english to TML like '/en/login'

How  i can archieve this ?
thanks

**Comment by jfarthing84** [comment]
This is not the proper [forum](https://wordpress.org/support/plugin/theme-my-login) for support.
