### ISSUE TITLE
Admin approval email not being sent ?

### ISSUE THREAD

**Issue by phenomlab** [jfarthing84/theme-my-login#53]
I have the latest version of WP installed (version 4.4.1), and the latest GIT version of TML. I am experiencing an issue where the admin approval email notification is not being sent. I'm also using Postman SMTP if this helps, but disabling this (and WangGuard) didn't seem to help. Any thoughts ?

Thanks

**Comment by phenomlab** [comment]
Interestingly, the denied emails are being sent ?

**Comment by phenomlab** [comment]
Just a bit more information - once the admin approves, the approval email is being sent to the user.

**Comment by jfarthing84** [comment]
So which notification is not being received? The one the let the admin know a user needs approved?

**Comment by phenomlab** [comment]
Yes. Exactly. 

Thanks

**Comment by jfarthing84** [comment]
You didn't disable it via the Custom E-mails module, did you?

**Comment by phenomlab** [comment]
No. Not using custom email. Treated on and off, and get the same result.

**Comment by jfarthing84** [comment]
But the user does get created and put into the "Pending" role, correct?

**Comment by phenomlab** [comment]
Yes. It's just the email that doesn't get sent to the admin

**Comment by jfarthing84** [comment]
Try disabling other plugins/checking server logs/settings. I just tested with a vanilla WP install and worked just fine.

**Comment by phenomlab** [comment]
Hmm. OK, thanks. I'm guessing that one of my plugins is interfering with a hook somewhere.

**Comment by phenomlab** [comment]
Jeff. Without disabling any plugins, I tried to resend the activation email and this seems to work. I then disabled all plugins, but TML still doesn't send the admin email !

**Comment by Colir** [comment]
+1....

**Comment by jfarthing84** [comment]
> Try disabling other plugins/checking server logs/settings. I just tested with a vanilla WP install and worked just fine.

**Comment by Colir** [comment]
Hi. For me this was due that i defined a new user as "pending" as the default role when registering
If i set it to "subscriber", it work well.
thanks.

**Comment by kylewhenderson** [comment]
I just ran into this issue as well, and setting the default user role in Settings->General to subscriber fixes that issue. I had my default set to a custom user role called "Customer". Any chance of a fix for this "gotcha"?

**Comment by jfarthing84** [comment]
@kylewhenderson Your issue is a new issue and should be treated as such.
