### ISSUE TITLE
Custom User Role defaulting if using email verification

### ISSUE THREAD

**Issue by malisa-agency** [jfarthing84/theme-my-login#55]
After adding `wp_update_user( array ('ID' => $user_ID, 'role' => $_REQUEST['userRole']) );` to  `tml_user_register( $user_id )` function in `theme-my-login-custom.php`, this is added to the user registration and entered correctly into user table.
If using email verification, on activation, this is removed and defaulting to wordpress default, if using authentification:none, this doesnt happen.
Is there a work around to prevent to deletion of roles after email verification?

Appreciate the hard work put in with this plugin.

**Comment by jfarthing84** [comment]
This is a question for the [support forum](https://wordpress.org/support/plugin/theme-my-login).
