### ISSUE TITLE
Reset Password from your-profile/

### ISSUE THREAD

**Issue by firelf15** [jfarthing84/theme-my-login#56]
Clean install WordPress 4.4.2
Twenty Sixteen theme 1.1
Active Plugins: Theme My Login 6.4.4

When a subscriber attempts to change their password, as soon as the user starts typing the password into **<input type="password" name="pass2" id="pass2"** 
the password that had been entered into **<input type="password" name="pass1" id="pass1"** 
is wiped out, making it impossible to change the password.
See in action: [https://drive.google.com/open?id=0B5DQgjLC9aIyTUZBY3dYTDhocFE](url)

`define( 'WP_DEBUG', true );` results in

> Notice: Trying to get property of non-object in /Users/monika/Sites/sandbox/webroot/wp-content/themes/twentysixteen/profile-form.php on line 37

Call Stack:
[PS-35_theme-my-login_call-stack.txt](https://github.com/jfarthing84/theme-my-login/files/135282/PS-35_theme-my-login_call-stack.txt)

Screenshots to confirm clean install:
Core:
![ps-35_theme-my-login_core](https://cloud.githubusercontent.com/assets/4031481/13126984/e00a188c-d581-11e5-87ba-182796ea8a99.png)

Theme:
![ps-35_theme-my-login_theme](https://cloud.githubusercontent.com/assets/4031481/13126907/6f181034-d581-11e5-90b4-2e920804c8cc.png)

Plugins:
![ps-35_theme-my-login_plugins](https://cloud.githubusercontent.com/assets/4031481/13126993/f09cf50c-d581-11e5-8b92-7adfbc647f16.png)

Settings we need in production and what were used in the video:
![ps-35_theme-my-login_settings-needed-in-production](https://cloud.githubusercontent.com/assets/4031481/13126683/558f78e2-d580-11e5-8d7f-f49fe2b223e9.png)

These two additional screenshots indicate a bug that may be related, but I'm not sure.
![ps-35_theme-my-login-settings_01](https://cloud.githubusercontent.com/assets/4031481/13126682/558ebf24-d580-11e5-8c37-b09152d7b013.png)
![ps-35_theme-my-login-settings_02](https://cloud.githubusercontent.com/assets/4031481/13126686/559125ca-d580-11e5-85e8-81bdd7ab7e20.png)

**Comment by jfarthing84** [comment]
The path of the notice points to the fact that your install is not entirely "clean". Try removing/renaming the `profile-form.php` within your Twenty Sixteen directory and see if it works properly after doing so.

**Comment by firelf15** [comment]
Righto. I thought I copied that from your plugin, because the client wants to customize the theme, but I'll double check.
