### ISSUE TITLE
Lost Password page shows odd error message

### ISSUE THREAD

**Issue by CuriousCactus** [jfarthing84/theme-my-login#59]
When I am not logged in and I click Lost Password I get these two messages:

"Please enter your username or email address. You will receive a link to create a new password via email."

"Your password reset link appears to be invalid. Please request a new link below."

The second message seems odd if I haven't tried to reset the password yet.

**Comment by jfarthing84** [comment]
That error is only output `if ( isset( $_REQUEST['error'] ) )`. Unable to reproduce this.
