### ISSUE TITLE
6.4 beta 1 breaks my design

### ISSUE THREAD

**Issue by Beee4life** [jfarthing84/theme-my-login#6]
as the title suggests, the plugin breaks my login page.
the site should be centered and the menu has a site-wide background.
now the site is aligned left and the menu only partial has a background.
see screenshot.

![150902-tml-login](https://cloud.githubusercontent.com/assets/4508731/9641885/5f61fb06-51b9-11e5-89ad-4a64083fee83.png)

**Comment by jfarthing84** [comment]
Can you post a "before" shot?

**Comment by Beee4life** [comment]
www.freerides.org/login/

this is a screenshot from the entire screen (so you can see the position)

![150902-tml-login-full-screen](https://cloud.githubusercontent.com/assets/4508731/9643108/3578631e-51c0-11e5-830e-9370b429bb5a.png)

**Comment by jfarthing84** [comment]
It looks like your theme adds the slug of the page to the body class. On the login page, this is "login". TML currently uses the class "login" to target styling for itself. With 7.0, all TML classes will be prefixed with "tml-". Not sure if I want to change that for this release, though.

**Comment by Beee4life** [comment]
so (theoretically) if I create an if statement for the login page it would be solved ???
any other pages I should take into consideration ?

**Comment by jfarthing84** [comment]
If you could stop your them from outputting "login" to the body class, yes.

**Comment by Beee4life** [comment]
Since I didn't remember addding it.... i looked for it... 
https://roots.io/plugins/soil/ provided the answer.

```
add_theme_support('soil-clean-up'); 
```

**Comment by Beee4life** [comment]
i have activated "Enable "theme-my-login.css". If that option is selected does my custom one just take priority over yours or is yours not loaded at all ?

If so, can I then leave that file empty and use custom templates for all pages with a custom class. I like to use my own classes anyway since i'm rebuilding my template according to [BEM](https://en.bem.info/).

**Comment by jfarthing84** [comment]
If that checkbox is checked and you have your own in your theme, only yours is loaded. So, yes, you could just keep it blank.

**Comment by sam-artuso** [comment]
@jfarthing84 this breaks my website too. I think that the right solution is for you not to use CSS selectors with names like `.login`. This is quite a common class name. Maybe you could namespace your CSS selectors by prefixing them with `.theme-my-login-*`?

**Comment by jfarthing84** [comment]
The main reason I didn't want to change the classes with this release is because everybody who uses custom templates will suddenly be unstyled (because the custom templates won't be updated with the new class name). In the 7.0 branch, all TML classes are prefixed with `.tml-`.

I suggest, instead, that those of you having this issue disable TML's stylesheet, or use a custom one for yourselves.

**Comment by Beee4life** [comment]
I was able to successfully keep my structure in the body class by doing what I described above...

So this issue is resolved for me. There are still some issues but I think they'll be dealt with in other topics.

**Comment by Beee4life** [comment]
I just installed 6.4-beta2 and I use (an empty) theme-my-login.css, which should disbale any of the plugin's css, but I just noticed there is some css loaded by the plugin, namely themed-profiles.css. This again screws up my css since my body has a class named profile (after the name of the page).

See this screenshot for the css that gets loaded.
![150913 themed-profiles](https://cloud.githubusercontent.com/assets/4508731/9834798/5cf715c0-59cc-11e5-8f72-c52f09b9b4e1.png)

How do I stop that css from loading ?

**Comment by jfarthing84** [comment]
Try a direct download of the 6.4 branch. I've updated all of the classes used to be prefixed with `tml-`. See 9189b52.

**Comment by Beee4life** [comment]
I'm not talking about the classes.... 

themed-profiles.css is loaded even though the checkbox use theme-my-login.css is ticked.

I bypassed it now but it was more to point out some css is still loaded, when the checkbox is ticked.

**Comment by jfarthing84** [comment]
My point is that the stylesheet no longer styles `.profile` but instead `.tml-profile`.

**Comment by Beee4life** [comment]
I understand..... I now changed all the classes manually, so it's a not an issue for me... 

I just wanted to point it out... because ideally it shouldn't be loaded at all imo
