### ISSUE TITLE
Generate Password is not Working

### ISSUE THREAD

**Issue by test04233** [jfarthing84/theme-my-login#61]
Generate Password is not Working

**Comment by jfarthing84** [comment]
Care to be more specific?

**Comment by sky4git** [comment]
I am having the same issue. In user profile page, when we click on Generate password button(WP 4.5+), it does nothing, no javascript error or anything. 

Will you please check it?

I will update you once I find something.

**Comment by sky4git** [comment]
Sorry, problem solved. 
I realised that footer wasn't loading properly, which stops loading necessary scripts WP.
