### ISSUE TITLE
using Themed Profile option for Authors renders users unable to update their profile.

### ISSUE THREAD

**Issue by StyxOfDynamite** [jfarthing84/theme-my-login#63]
Hi,

I'm hitting the following line of code when trying to edit the logged in users profile.

```
if ( ! current_user_can( 'edit_user', $current_user->ID ) )
    wp_die( __( 'You do not have permission to edit this user.', 'theme-my-login' ) );
```

I don't think the `edit_user` capability should be assigned as this would, to my understanding allow the editing of all users not just the the current user.

A proposed fix would be to check whether the user is updating their own profile, something akin to

```
if ( !current_user_can('edit_user', $user_id) && $user_id != $current_user->ID )
    wp_die( __( 'You do not have permission to edit this user.', 'theme-my-login' ) );
```

I'm confident the issue is with the plugin as disabling themed profiles for authors allows the user to update their own profile using the standard word press profile administration page.

**Comment by jfarthing84** [comment]
The function `current_user_can()` eventually calls `map_meta_cap()`, which already checks if the current user is the user attempting to be edited. You have another conflict with your permissions.

**Comment by StyxOfDynamite** [comment]
Thanks for the speedy response,

Can you shed any light onto why disabling themed profiles removes the permissions issue?

**Comment by jfarthing84** [comment]
Not sure. Those same 2 lines of code are also present on `wp-admin/edit-user.php`, which is included by `wp-admin/profile.php`.
