### ISSUE TITLE
Email moderation - unable to confirm email address

### ISSUE THREAD

**Issue by johnhollier** [jfarthing84/theme-my-login#64]
(I just installed TML.  When I got this error I deactivated all other plugins and switched to the WP Twenty Sixteen theme.)

When I click on (copy/paste) the link in the "Activate Your Account" email it takes me to http://www.biz1sthosting.com/wp-login.php?action=activate - i.e., it strips out the activation key and userid.

If I enter the userid and password on this screen I get redirected to the wp-login.php screen with the following message:
ERROR: You have not yet confirmed your e-mail address. Resend activation?

What did I set up incorrectly?

Thanks

John H.

**Comment by jfarthing84** [comment]
This is not the proper forum for support requests.
