### ISSUE TITLE
Custom Emails Save Bug(s)

### ISSUE THREAD

**Issue by rk** [jfarthing84/theme-my-login#67]
On a fresh install of WordPress/Theme My Login, after custom emails addon is activated, the first time the emails page is saved _all_ admin notifications are disabled regardless of their checked/unchecked state.

The **E-mail Format** field resets to Plain Text after selecting HTML and clicking save.

These are small issues, but can cause significant issues/misunderstanding if a user isn't attentive. I don't trust our clients to update email templates at the moment.

WordPress 4.5.2
Theme My Login 6.4.4

**Comment by jfarthing84** [comment]
I definitely get the first issue - but not the second.

**Comment by rk** [comment]
I'm not certain how to give you steps to reproduce the 2nd issue, but every time I load the TML email settings any HTML format emails have "Plain Text" selected. I've checked the markup (the selected tag is on the plain text value) and the DB (the HTML content type is saved).

If I have a few minutes free time this week, I'll dig in and see if I can find the cause.

**Comment by rk** [comment]
I found the issue and will open a pull request shortly. Looks like a simple copy/paste issue in `custom-email-admin.php` on lines 503 - 504.

**Comment by jfarthing84** [comment]
Good find, sir!
