### ISSUE TITLE
"Your password reset link appears to be invalid. Please request a new link below."

### ISSUE THREAD

**Issue by shawnhooper** [jfarthing84/theme-my-login#7]
Hi Jeff,

I'm testing this beta against:
- WordPress 4.3 (Release)
- Twentyfifteen Theme
- Theme My Login Beta Plugin
- wpmandrill (plugin)

I can request my lost password e-mail.  I can click on the recovery link in the e-mail, and get the change password screen.  When I submit that, I get:

"Your password reset link appears to be invalid. Please request a new link below."

What could I be missing?  Thanks in advance for your help, it's very much appreciated !

**Comment by jfarthing84** [comment]
Could you temporarily disable other plugins and try again?

**Comment by shawnhooper** [comment]
The only other plugin is wpmandrill which overrides wp_mail.   I can't disable it, or I won't get the e-mail message in the first place. My servers have no built-in mail capability.

**Comment by jfarthing84** [comment]
Could I possibly test? You can send credentials [here](http://www.jfarthing.com/contact/).

**Comment by goredshift** [comment]
I have updated to the Beta as well.  With 6.3 and the 6.4 plugin installed no errors are generated but the password reset did not work still for me.  When I removed 6.3 and went only with the beta a Fatal error was generated and the plugin would not activate.  
Thanks
GL

**Comment by jfarthing84** [comment]
Well, you definitely can't have boh active! You have to rename the beta directory to "theme-my-login".

**Comment by goredshift** [comment]
ok.. That makes sense.  Thanks.

**Comment by KenPixelMii** [comment]
Using 6.4 on WordPress 4.3.1 using Divi theme;
Reset password, email link works, new password chosen, back to login screen (enter new credentials) - [ISSUE STARTS HERE] I am in fact logged in but the page shows the invalid link error (see img). For our non-admin users we are hiding the admin bar so they don't know they are logged in unless they happen to see that Login has changed to Log Out in the nav. 
<img width="1222" alt="screen shot 2015-09-22 at 9 52 49 pm" src="https://cloud.githubusercontent.com/assets/2380384/10036394/3b8077c8-6175-11e5-9b0d-2c324588cc0b.png">

**Comment by jfarthing84** [comment]
It appears to be redirecting you back to the referer. Are you using the Custom Redirection module?

**Comment by goredshift** [comment]
Hey. Not sure how I got on this thread but it doesn’t seem to relate to me.  Good luck with the solution though! 

Peace, 
Glenn

Tel: 205.614.3001  |  glenn.lewis@thinkred.co mailto:glenn@thinkred.co | Follow me on Facebook http://www.facebook.com/goredshift | www.thinkred.co http://www.thinkred.us/

The information contained within the referenced, linked, or directed email communication is intended to be a confidential communication between the original sender and recipient, and is to be treated as confidential. All works, ideas, or copy within are copyrighted by Red Shift Creative, LLC., and are not to be used in any manner other by which they were intended by Red Shift Creative, LLC. If you believe you have received this or any other email in error, please contact postmaster@goredshift.com mailto:postmaster@goredshift.com

**Comment by KenPixelMii** [comment]
Thanks Jeff, 

I was using Custom Redirection and the referer setting. I guess I didn't recall in the past where the referer setting would effect password resets. I've updated the settings to custom location (home page) for now. Curious if there is a way I can still use "referer" without causing the invalid link on password resets.

**Comment by jfarthing84** [comment]
@KenPixelMii Can you open a new issue for yours? I'm going to assume @shawnhooper's issue was fixed with the 6.4 release.

**Comment by shawnhooper** [comment]
Hi @jfarthing84 - 

Sorry, I only got back to this issue today.  Yes, 6.4, along with a fix to my theme resolved this issue. Thanks for the new version! 

Cheers.

**Comment by alexmigf** [comment]
Hi,

I'm using the last version of the Plugin and Wordpress, and without switching off the redirections the key doesn't work.

**Comment by jfarthing84** [comment]
@alexmigf It sounds like you may be experiencing #27.

**Comment by alexmigf** [comment]
Yes, i will add redirects to functions.php and leave this option off.

**Comment by johnvlittle** [comment]
We also have this issue.  Every user is locked out, noone can reset their passwords. This seems like a pretty serious bug - in 20 years we have never seen this with any other system. 
If it is a cache issue, How exactly does one disable cache?  Is this at the ISP, server or wordpress level?  Please give a non-tech answer.
