### ISSUE TITLE
Username Won't Autofill

### ISSUE THREAD

**Issue by rpounds1986** [jfarthing84/theme-my-login#71]
When I check remember me and login and logout, the username flickers and disappears and I have to re enter it.
![untitled](https://cloud.githubusercontent.com/assets/19418078/16164876/5b941a6c-3495-11e6-8122-5482d78df73a.png)

**Comment by jfarthing84** [comment]
The "Remember Me" checkbox doesn't work like that - it merely makes the cookie last longer than normal. You're thinking of your browsers password saving mechanism.
