### ISSUE TITLE
Throws warnings when integrated with some plugins for social connect (accesspress)

### ISSUE THREAD

**Issue by omerfarooX** [jfarthing84/theme-my-login#72]
The plugin throws warnings when its connected with plugins for social login. I was using accesspress when i encountered these errors. These are pretty minor warnings and i would have expected them to just go through and load rest of the page but for some reason the script doesn't execute after these warnings.

I guess these warnings are thrown because the admin panel has been disabled for roles like subscribers and so couldn't find anywhere to send the user. Even though i had created the login and logout redirection to land on the home page.

```
Warning: Missing argument 2 for Theme_My_Login_Custom_Redirection::login_redirect() in ***/theme-my-login/modules/custom-redirection/custom-redirection.php on line 199

Warning: Missing argument 3 for Theme_My_Login_Custom_Redirection::login_redirect() in ***/theme-my-login/modules/custom-redirection/custom-redirection.php on line 199

Warning: Cannot modify header information - headers already sent by (output started at ***/theme-my-login/modules/custom-redirection/custom-redirection.php:199) in /wp-includes/pluggable.php on line 1171
```

The url at this point was something like this:
http://mysite.com/index.php?apsl_login_id=google_check&redirect_to=http://mysite.com/wp-admin#

Anyways fixing them was preety simple just initiated with some default values when the values where not found. So in theme-my-login/modules/custom-redirection/custom-redirection.php on line 199 replace this 

```
public function login_redirect( $redirect_to, $request, $user) {
                                           with 
public function login_redirect( $redirect_to, $request = null, $user = null ) {

```

I think this change should be made to the repository, as it doesn't do any harm and just make the plugin a bit more smarter in handling different kind of requests.

**Comment by jfarthing84** [comment]
In core, all three parameters are always present when the filter is called. Other plugins should follow suit - raise the issue with them.
