### ISSUE TITLE
Log in, Register, Lost Password ButtonTitles can't be tranlated or modified.

### ISSUE THREAD

**Issue by razcakappa** [jfarthing84/theme-my-login#77]
As the subject says, "Login", "Register","Lost Password" button titles can't be modified. This heavily affects the translatability of each wording. When browsing through the code, found this:
_theme-my-login/includes/class-theme-my-login-template.php_ line 152

`if ( $page_id = Theme_My_Login::get_page_id( $action ) ) {
         $title = get_post_field( 'post_title', $page_id );
} else {...}`

Which means every time button titles get the page's titles. So on translated web sites should have translated title per each page. This is very difficult. And in the code, there's a else part which we can assign custom wordings, and its more useful. 

However as per the `if ( $page_id = Theme_My_Login::get_page_id( $action ) )`  condition it never falls to `else` part to access custom wording. Is there any particular reason why you have that page title assigning for buttons?

[Pull Request - #76](https://github.com/jfarthing84/theme-my-login/pull/76)
I've altered the code to remove above condition. Is there any better suggestion or method for this issue?

thanks

**Comment by jfarthing84** [comment]
Explained in #76.
