### ISSUE TITLE
Reset Password email not firing for user

### ISSUE THREAD

**Issue by defensivedepth** [jfarthing84/theme-my-login#78]
WP 4.5.3 on WPEngine, TML 6.4.5.

TML Modules Enabled: _Email / Redirection / User Links / Themed Profiles / User Moderation_

I am working on customizing emails for the Lost Password functionality at the Login screen.

I have customized the Retrieve Password Email, and that is working just fine.

However, when I customize the Reset Password Email, (the confirmation of a password change) the user requesting the reset never receives it - the admin receives the customized email just fine.

Is this a known issue?

Thanks,

**Comment by defensivedepth** [comment]
Just saw this, not sure if it is related or not....  #65

**Comment by jfarthing84** [comment]
TML actually doesn't yet handle the user password change notification . What you are customizing is the admin notification.

**Comment by defensivedepth** [comment]
Ah, that was not clear. Thanks
