### ISSUE TITLE
WPML compatibility

### ISSUE THREAD

**Issue by ocReaper** [jfarthing84/theme-my-login#79]
Hi @jfarthing84!

I have a little problem with `Theme_My_Login::get_page_link()` function since it's using the `Theme_My_Login::get_page_id()` function which looks up for specific meta of a post via plain SQL. The problem with that with WPML I have a translation of a logout page which gives me the page ID of the original language and I have to turn it into the current language version.

One option will be a new filter where I can change the retured id.

``` php
/**
 * Retrieves a page ID for an action
 *
 * @since 6.3
 *
 * @param string $action The action
 * @return int|bool The page ID if exists, false otherwise
 */
public static function get_page_id( $action ) {
    global $wpdb;

    if ( 'rp' == $action )
        $action = 'resetpass';
    elseif ( 'retrievepassword' == $action )
        $action = 'lostpassword';

    if ( ! $page_id = wp_cache_get( $action, 'tml_page_ids' ) ) {
        $page_id = $wpdb->get_var( $wpdb->prepare( "SELECT p.ID FROM $wpdb->posts p LEFT JOIN $wpdb->postmeta pmeta ON p.ID = pmeta.post_id WHERE p.post_type = 'page' AND pmeta.meta_key = '_tml_action' AND pmeta.meta_value = %s", $action ) );
        if ( ! $page_id )
            return null;
        wp_cache_add( $action, $page_id, 'tml_page_ids' );
    }
    return apply_filters( 'tml_page_id', $page_id, $action );
}
```

The other is using wpml specific conditions like:

``` php
if ( function_exists( 'wpml_object_id_filter' ) ) {
  $page_id = wpml_object_id_filter( $page_id, 'page', true, ICL_LANGUAGE_CODE );
}
```

I'll make a pull request if you'd like to.

**Comment by jfarthing84** [comment]
You couldn't just use the `tml_page_link` filter instead?

**Comment by ocReaper** [comment]
It's much more cleaner to use the ID, since WPML works with the ID's. Using the link would require unnecessary string exploding and database query to obtain the page ID and pass it to WPML for another query.

**Comment by ocReaper** [comment]
Thanks for the support!
