### ISSUE TITLE
Disable Notification not staying checked & Confirmation & Admin query

### ISSUE THREAD

**Issue by jpopuk** [jfarthing84/theme-my-login#81]
Hi, I downloaded your plugin (great work), and themed all the login/ registration pages etc to exactly how I require them.

On testing, I noticed that when I check 'Disable Notification' under User Denial, and click Save Changes, it does not stay checked, and does not work (still sends denial email).

Is there a fix for this?

Also, I have a query regarding the email confirmation & admin approval... Is it difficult to have both options enabled? I would like a user to confirm their email first, and then be approved after.

Is this feasible, and if so what would be the best way to go about doing this?

Thanks, and great work! :)

**Comment by jpopuk** [comment]
Just realised you have updated some files in the past few days... (downloaded plugin direct from WordPress website)... Updated, and the Disable Notification looks to be fixed! Great work...

If you could let me know about the email confirmation & admin approval query, that would be great! - That feature would be the cherry on the cake, as this plugin is superb!

**Comment by jfarthing84** [comment]
There is currently no built-in way to enable both, but I will look into it in the future.

**Comment by jpopuk** [comment]
Really appreciate your response on this. Would be a great feature to add :) .. Thanks again!
