### ISSUE TITLE
Emails are not being sent when a new user is registered

### ISSUE THREAD

**Issue by rrikesh** [jfarthing84/theme-my-login#82]
No emails are being sent to the admin and to the new user when a new user registers on the site (and automatically set to status pending as _moderation type_ is set to _admin approval_). However emails are successfully sent to users when they are approved.

TML Settings:
General:

> Login Type: Email only
> 
> Modules:
> Custom Email
> Security
> Themed Profile
> User Moderation

Moderation

> Moderation Type: Admin Approval

I have deactivated all plugins except the following:

> Theme My Login
> WP Mail Logging
> WP-Mail-SMTP

Am I doing anything wrong?

Thanks

**Comment by jfarthing84** [comment]
When "Admin Approval" is the moderation method, no email is sent until they are approved. This is by design.
