### ISSUE TITLE
Action Links not passed through __()

### ISSUE THREAD

**Issue by samiamsam** [jfarthing84/theme-my-login#88]
The Action LInks are not always translated.

In https://github.com/jfarthing84/theme-my-login/blob/6.4/includes/class-theme-my-login-template.php#L153

`$title = get_post_field( 'post_title', $page_id );`

Should become

`$title = __(get_post_field( 'post_title', $page_id ), 'theme-my-login');`

Sorry this isn't a pull request.

**Comment by jfarthing84** [comment]
This is useless as there is no way to pull the output of a function into the PO file.
