### ISSUE TITLE
Moderation is skipped when log in with email is enabled

### ISSUE THREAD

**Issue by mjcoop** [jfarthing84/theme-my-login#92]
If Email confirmation moderation is enabled and log in with email address or username is enabled, users can log in using their email address before an account is activated. Their role stays as pending but they are logged in.

Source of the issue appears to be in modules/user-moderation/user-moderation.php line 153.
`if ( $userdata = get_user_by( 'login', $username ) ) {`

I also have custom passwords enabled... I suppose that might also be part of the issue.

**Comment by jfarthing84** [comment]
Which WordPress version does this affect?

**Comment by jfarthing84** [comment]
Fixed in 4cc11b010e763e4d5977517a76476b629091f218.
