### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by Zoroaster54** [jfarthing84/theme-my-login#94]
Using the TML widget (last version), all is fine (i.e. translated) except error message when entering wrong username or password.
The message “ERROR: The username or password you entered is incorrect. Lost your password?” still shows in English. Digged into po/pot-files, in Plugin-language directory and in general wp-content/languages/plugins directory to find position of that english text, but no luck.
Could you point into the right direction please?

**Comment by jfarthing84** [comment]
That string is from WP core.
