### ISSUE TITLE
Recapcha PHP warning about calling reset on null

### ISSUE THREAD

**Issue by mkellyxp** [jfarthing84/theme-my-login#97]
When registration fails because of some other error, but recaptcha succeeds, a php warning is fired because it’s calling reset() on a null value.

I have created a fix branch and can push it up to you if you wish.

![screen shot 2016-11-15 at 8 44 30 am](https://cloud.githubusercontent.com/assets/6528226/20317044/5301e898-ab19-11e6-9491-2912008fa6df.png)

**Comment by jfarthing84** [comment]
I'd be interested to see the reponse you were getting from reCAPTCHA, as the `error-codes` array should be populated if `success` is `false`.

**Comment by mkellyxp** [comment]
So I added some logging in here.

```
        if ( 200 == $response_code ) {

            error_log($response_code);
            error_log($response_message);
            error_log($response_body);

            $result = json_decode( $response_body, true );

            if ( $result['success'] )
                return true;

            return new WP_Error( 'recaptcha', reset( $result['error-codes'] ) );
        }
```

and that produced

```
[15-Nov-2016 19:04:19 UTC] 200
[15-Nov-2016 19:04:19 UTC] OK
[15-Nov-2016 19:04:19 UTC] {
  "success": true,
  "challenge_ts": "2016-11-15T19:14:06Z",
  "hostname": "ok.hbs.dev"
}
[15-Nov-2016 19:04:20 UTC] 200
[15-Nov-2016 19:04:20 UTC] OK
[15-Nov-2016 19:04:20 UTC] {
  "success": false,
  "challenge_ts": "2016-11-15T19:14:06Z",
  "hostname": "ok.hbs.dev"
}
[15-Nov-2016 19:04:20 UTC] PHP Warning:  reset() expects parameter 1 to be array, null given in /srv/www/ok-hbs/htdocs/wp-content/plugins/theme-my-login/modules/recaptcha/recaptcha.php on line 191
```

**Comment by mkellyxp** [comment]
[15-Nov-2016 19:04:19 UTC] 200
[15-Nov-2016 19:04:19 UTC] OK
[15-Nov-2016 19:04:19 UTC] {
  "success": true,
  "challenge_ts": "2016-11-15T19:14:06Z",
  "hostname": "ok.hbs.dev"
}
[15-Nov-2016 19:04:20 UTC] 200
[15-Nov-2016 19:04:20 UTC] OK
[15-Nov-2016 19:04:20 UTC] {
  "success": false,
  "challenge_ts": "2016-11-15T19:14:06Z",
  "hostname": "ok.hbs.dev"
}
[15-Nov-2016 19:04:20 UTC] PHP Warning:  reset() expects parameter 1 to be array, null given in /srv/www/ok-hbs/htdocs/wp-content/plugins/theme-my-login/modules/recaptcha/recaptcha.php on line 191

**Comment by jfarthing84** [comment]
What user action was taken to produce these requests?

**Comment by mkellyxp** [comment]
On an MU site.. trying to register.  /register/?blog_id=1

When everything is entered correctly, it works, no warning, and if the captcha is really incorrect, it is also fine.

This bug seems to persist when I do the captcha correctly, but something else fails in the user reg process

**Comment by mkellyxp** [comment]
Just wanted to follow up on this.  Did a bit more digging and seems in wpmu_validate_signup it calls registration_errors, which would mean it's getting called twice by TML.

Looks like it may need to ensure if it's running on multisite to not run recaptcha_validate twice.

**Comment by mkellyxp** [comment]
My apologies here.  We ended up having an extra hook somewhere else in the code, and therefor just had to modify OUR theme slightly.  This appears not to be an issue.  Thanks again.
